// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: protocli/actor.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActorCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorCreateRequest) Reset() {
	*x = ActorCreateRequest{}
	mi := &file_protocli_actor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorCreateRequest) ProtoMessage() {}

func (x *ActorCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_actor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorCreateRequest.ProtoReflect.Descriptor instead.
func (*ActorCreateRequest) Descriptor() ([]byte, []int) {
	return file_protocli_actor_proto_rawDescGZIP(), []int{0}
}

type ActorCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           string                 `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorCreateResponse) Reset() {
	*x = ActorCreateResponse{}
	mi := &file_protocli_actor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorCreateResponse) ProtoMessage() {}

func (x *ActorCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_actor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorCreateResponse.ProtoReflect.Descriptor instead.
func (*ActorCreateResponse) Descriptor() ([]byte, []int) {
	return file_protocli_actor_proto_rawDescGZIP(), []int{1}
}

func (x *ActorCreateResponse) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

type ActorUseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           string                 `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActorUseRequest) Reset() {
	*x = ActorUseRequest{}
	mi := &file_protocli_actor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActorUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActorUseRequest) ProtoMessage() {}

func (x *ActorUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_actor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActorUseRequest.ProtoReflect.Descriptor instead.
func (*ActorUseRequest) Descriptor() ([]byte, []int) {
	return file_protocli_actor_proto_rawDescGZIP(), []int{2}
}

func (x *ActorUseRequest) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

var File_protocli_actor_proto protoreflect.FileDescriptor

const file_protocli_actor_proto_rawDesc = "" +
	"\n" +
	"\x14protocli/actor.proto\x12\bprotocli\"\x14\n" +
	"\x12ActorCreateRequest\"'\n" +
	"\x13ActorCreateResponse\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\tR\x03aid\"#\n" +
	"\x0fActorUseRequest\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\tR\x03aidB\x11Z\x0fzgame/pb/golangb\x06proto3"

var (
	file_protocli_actor_proto_rawDescOnce sync.Once
	file_protocli_actor_proto_rawDescData []byte
)

func file_protocli_actor_proto_rawDescGZIP() []byte {
	file_protocli_actor_proto_rawDescOnce.Do(func() {
		file_protocli_actor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocli_actor_proto_rawDesc), len(file_protocli_actor_proto_rawDesc)))
	})
	return file_protocli_actor_proto_rawDescData
}

var file_protocli_actor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protocli_actor_proto_goTypes = []any{
	(*ActorCreateRequest)(nil),  // 0: protocli.ActorCreateRequest
	(*ActorCreateResponse)(nil), // 1: protocli.ActorCreateResponse
	(*ActorUseRequest)(nil),     // 2: protocli.ActorUseRequest
}
var file_protocli_actor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocli_actor_proto_init() }
func file_protocli_actor_proto_init() {
	if File_protocli_actor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocli_actor_proto_rawDesc), len(file_protocli_actor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocli_actor_proto_goTypes,
		DependencyIndexes: file_protocli_actor_proto_depIdxs,
		MessageInfos:      file_protocli_actor_proto_msgTypes,
	}.Build()
	File_protocli_actor_proto = out.File
	file_protocli_actor_proto_goTypes = nil
	file_protocli_actor_proto_depIdxs = nil
}
