// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: bag.proto

package gamelogic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单物品信息
type ItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`            //唯一编号
	ItemCfgId     int32                  `protobuf:"varint,2,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"` //配表id
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`                                //数量
	ExtInfo       string                 `protobuf:"bytes,100,opt,name=ext_info,json=extInfo,proto3" json:"ext_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	mi := &file_bag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{0}
}

func (x *ItemData) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemData) GetItemCfgId() int32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *ItemData) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *ItemData) GetExtInfo() string {
	if x != nil {
		return x.ExtInfo
	}
	return ""
}

// 获取背包请求
type GetBagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBagRequest) Reset() {
	*x = GetBagRequest{}
	mi := &file_bag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBagRequest) ProtoMessage() {}

func (x *GetBagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBagRequest.ProtoReflect.Descriptor instead.
func (*GetBagRequest) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{1}
}

// 获取背包响应
type GetBagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ResultErr             `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Data          []*ItemData            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBagResponse) Reset() {
	*x = GetBagResponse{}
	mi := &file_bag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBagResponse) ProtoMessage() {}

func (x *GetBagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBagResponse.ProtoReflect.Descriptor instead.
func (*GetBagResponse) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{2}
}

func (x *GetBagResponse) GetErr() *ResultErr {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetBagResponse) GetData() []*ItemData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 使用道具
type BagItemUseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` //背包物品中的编号
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                     //使用数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItemUseRequest) Reset() {
	*x = BagItemUseRequest{}
	mi := &file_bag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItemUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemUseRequest) ProtoMessage() {}

func (x *BagItemUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemUseRequest.ProtoReflect.Descriptor instead.
func (*BagItemUseRequest) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{3}
}

func (x *BagItemUseRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BagItemUseRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 使用道具返回
type BagItemUseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                  // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // 消息
	ItemData      *ItemData              `protobuf:"bytes,3,opt,name=item_data,json=itemData,proto3" json:"item_data,omitempty"` //请求物品的信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItemUseResponse) Reset() {
	*x = BagItemUseResponse{}
	mi := &file_bag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItemUseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemUseResponse) ProtoMessage() {}

func (x *BagItemUseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemUseResponse.ProtoReflect.Descriptor instead.
func (*BagItemUseResponse) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{4}
}

func (x *BagItemUseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BagItemUseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BagItemUseResponse) GetItemData() *ItemData {
	if x != nil {
		return x.ItemData
	}
	return nil
}

// 道具变化通知
type SyncBagItemChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*ItemData            `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncBagItemChange) Reset() {
	*x = SyncBagItemChange{}
	mi := &file_bag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncBagItemChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncBagItemChange) ProtoMessage() {}

func (x *SyncBagItemChange) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncBagItemChange.ProtoReflect.Descriptor instead.
func (*SyncBagItemChange) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{5}
}

func (x *SyncBagItemChange) GetData() []*ItemData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_bag_proto protoreflect.FileDescriptor

const file_bag_proto_rawDesc = "" +
	"\n" +
	"\tbag.proto\x12\bprotocli\x1a\n" +
	"base.proto\"p\n" +
	"\bItemData\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1e\n" +
	"\vitem_cfg_id\x18\x02 \x01(\x05R\titemCfgId\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\x12\x19\n" +
	"\bext_info\x18d \x01(\tR\aextInfo\"\x0f\n" +
	"\rGetBagRequest\"_\n" +
	"\x0eGetBagResponse\x12%\n" +
	"\x03err\x18\x01 \x01(\v2\x13.protocli.ResultErrR\x03err\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.protocli.ItemDataR\x04data\">\n" +
	"\x11BagItemUseRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"y\n" +
	"\x12BagItemUseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\titem_data\x18\x03 \x01(\v2\x12.protocli.ItemDataR\bitemData\";\n" +
	"\x11SyncBagItemChange\x12&\n" +
	"\x04data\x18\x02 \x03(\v2\x12.protocli.ItemDataR\x04dataB\x1bZ\x19zgame/pb/golang/gamelogicb\x06proto3"

var (
	file_bag_proto_rawDescOnce sync.Once
	file_bag_proto_rawDescData []byte
)

func file_bag_proto_rawDescGZIP() []byte {
	file_bag_proto_rawDescOnce.Do(func() {
		file_bag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bag_proto_rawDesc), len(file_bag_proto_rawDesc)))
	})
	return file_bag_proto_rawDescData
}

var file_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_bag_proto_goTypes = []any{
	(*ItemData)(nil),           // 0: protocli.ItemData
	(*GetBagRequest)(nil),      // 1: protocli.GetBagRequest
	(*GetBagResponse)(nil),     // 2: protocli.GetBagResponse
	(*BagItemUseRequest)(nil),  // 3: protocli.BagItemUseRequest
	(*BagItemUseResponse)(nil), // 4: protocli.BagItemUseResponse
	(*SyncBagItemChange)(nil),  // 5: protocli.SyncBagItemChange
	(*ResultErr)(nil),          // 6: protocli.ResultErr
}
var file_bag_proto_depIdxs = []int32{
	6, // 0: protocli.GetBagResponse.err:type_name -> protocli.ResultErr
	0, // 1: protocli.GetBagResponse.data:type_name -> protocli.ItemData
	0, // 2: protocli.BagItemUseResponse.item_data:type_name -> protocli.ItemData
	0, // 3: protocli.SyncBagItemChange.data:type_name -> protocli.ItemData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bag_proto_init() }
func file_bag_proto_init() {
	if File_bag_proto != nil {
		return
	}
	file_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bag_proto_rawDesc), len(file_bag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bag_proto_goTypes,
		DependencyIndexes: file_bag_proto_depIdxs,
		MessageInfos:      file_bag_proto_msgTypes,
	}.Build()
	File_bag_proto = out.File
	file_bag_proto_goTypes = nil
	file_bag_proto_depIdxs = nil
}
