// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: protocli/bag.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 单物品信息
type ItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`            //唯一编号
	ItemCfgId     int32                  `protobuf:"varint,2,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"` //配表id
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`                                //数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemData) Reset() {
	*x = ItemData{}
	mi := &file_protocli_bag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemData) ProtoMessage() {}

func (x *ItemData) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemData.ProtoReflect.Descriptor instead.
func (*ItemData) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{0}
}

func (x *ItemData) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *ItemData) GetItemCfgId() int32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *ItemData) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 添加物品请求
type AddItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 物品ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemRequest) Reset() {
	*x = AddItemRequest{}
	mi := &file_protocli_bag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemRequest) ProtoMessage() {}

func (x *AddItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemRequest.ProtoReflect.Descriptor instead.
func (*AddItemRequest) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{1}
}

func (x *AddItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *AddItemRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 添加物品响应
type AddItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddItemResponse) Reset() {
	*x = AddItemResponse{}
	mi := &file_protocli_bag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddItemResponse) ProtoMessage() {}

func (x *AddItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddItemResponse.ProtoReflect.Descriptor instead.
func (*AddItemResponse) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{2}
}

func (x *AddItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 移除物品请求
type RemoveItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` // 物品ID
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                // 数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemRequest) Reset() {
	*x = RemoveItemRequest{}
	mi := &file_protocli_bag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemRequest) ProtoMessage() {}

func (x *RemoveItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemRequest.ProtoReflect.Descriptor instead.
func (*RemoveItemRequest) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *RemoveItemRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 移除物品响应
type RemoveItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveItemResponse) Reset() {
	*x = RemoveItemResponse{}
	mi := &file_protocli_bag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveItemResponse) ProtoMessage() {}

func (x *RemoveItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveItemResponse.ProtoReflect.Descriptor instead.
func (*RemoveItemResponse) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{4}
}

func (x *RemoveItemResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取背包请求
type GetBagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBagRequest) Reset() {
	*x = GetBagRequest{}
	mi := &file_protocli_bag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBagRequest) ProtoMessage() {}

func (x *GetBagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBagRequest.ProtoReflect.Descriptor instead.
func (*GetBagRequest) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{5}
}

// 获取背包响应
type GetBagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                                                   // 是否成功
	Bag           map[string]int32       `protobuf:"bytes,2,rep,name=bag,proto3" json:"bag,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 背包物品
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                                                                    // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBagResponse) Reset() {
	*x = GetBagResponse{}
	mi := &file_protocli_bag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBagResponse) ProtoMessage() {}

func (x *GetBagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBagResponse.ProtoReflect.Descriptor instead.
func (*GetBagResponse) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{6}
}

func (x *GetBagResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetBagResponse) GetBag() map[string]int32 {
	if x != nil {
		return x.Bag
	}
	return nil
}

func (x *GetBagResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 使用道具
type BagItemUseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"` //背包物品中的编号
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                     //使用数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItemUseRequest) Reset() {
	*x = BagItemUseRequest{}
	mi := &file_protocli_bag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItemUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemUseRequest) ProtoMessage() {}

func (x *BagItemUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemUseRequest.ProtoReflect.Descriptor instead.
func (*BagItemUseRequest) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{7}
}

func (x *BagItemUseRequest) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BagItemUseRequest) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 使用道具返回
type BagItemUseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                  // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                   // 消息
	ItemData      *ItemData              `protobuf:"bytes,3,opt,name=item_data,json=itemData,proto3" json:"item_data,omitempty"` //请求物品的信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItemUseResponse) Reset() {
	*x = BagItemUseResponse{}
	mi := &file_protocli_bag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItemUseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemUseResponse) ProtoMessage() {}

func (x *BagItemUseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_bag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemUseResponse.ProtoReflect.Descriptor instead.
func (*BagItemUseResponse) Descriptor() ([]byte, []int) {
	return file_protocli_bag_proto_rawDescGZIP(), []int{8}
}

func (x *BagItemUseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BagItemUseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BagItemUseResponse) GetItemData() *ItemData {
	if x != nil {
		return x.ItemData
	}
	return nil
}

var File_protocli_bag_proto protoreflect.FileDescriptor

const file_protocli_bag_proto_rawDesc = "" +
	"\n" +
	"\x12protocli/bag.proto\x12\bprotocli\"U\n" +
	"\bItemData\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1e\n" +
	"\vitem_cfg_id\x18\x02 \x01(\x05R\titemCfgId\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\"?\n" +
	"\x0eAddItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"E\n" +
	"\x0fAddItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"B\n" +
	"\x11RemoveItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"H\n" +
	"\x12RemoveItemResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x0f\n" +
	"\rGetBagRequest\"\xb1\x01\n" +
	"\x0eGetBagResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x123\n" +
	"\x03bag\x18\x02 \x03(\v2!.protocli.GetBagResponse.BagEntryR\x03bag\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x1a6\n" +
	"\bBagEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\">\n" +
	"\x11BagItemUseRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"y\n" +
	"\x12BagItemUseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12/\n" +
	"\titem_data\x18\x03 \x01(\v2\x12.protocli.ItemDataR\bitemDataB\x11Z\x0fzgame/pb/golangb\x06proto3"

var (
	file_protocli_bag_proto_rawDescOnce sync.Once
	file_protocli_bag_proto_rawDescData []byte
)

func file_protocli_bag_proto_rawDescGZIP() []byte {
	file_protocli_bag_proto_rawDescOnce.Do(func() {
		file_protocli_bag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocli_bag_proto_rawDesc), len(file_protocli_bag_proto_rawDesc)))
	})
	return file_protocli_bag_proto_rawDescData
}

var file_protocli_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_protocli_bag_proto_goTypes = []any{
	(*ItemData)(nil),           // 0: protocli.ItemData
	(*AddItemRequest)(nil),     // 1: protocli.AddItemRequest
	(*AddItemResponse)(nil),    // 2: protocli.AddItemResponse
	(*RemoveItemRequest)(nil),  // 3: protocli.RemoveItemRequest
	(*RemoveItemResponse)(nil), // 4: protocli.RemoveItemResponse
	(*GetBagRequest)(nil),      // 5: protocli.GetBagRequest
	(*GetBagResponse)(nil),     // 6: protocli.GetBagResponse
	(*BagItemUseRequest)(nil),  // 7: protocli.BagItemUseRequest
	(*BagItemUseResponse)(nil), // 8: protocli.BagItemUseResponse
	nil,                        // 9: protocli.GetBagResponse.BagEntry
}
var file_protocli_bag_proto_depIdxs = []int32{
	9, // 0: protocli.GetBagResponse.bag:type_name -> protocli.GetBagResponse.BagEntry
	0, // 1: protocli.BagItemUseResponse.item_data:type_name -> protocli.ItemData
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocli_bag_proto_init() }
func file_protocli_bag_proto_init() {
	if File_protocli_bag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocli_bag_proto_rawDesc), len(file_protocli_bag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocli_bag_proto_goTypes,
		DependencyIndexes: file_protocli_bag_proto_depIdxs,
		MessageInfos:      file_protocli_bag_proto_msgTypes,
	}.Build()
	File_protocli_bag_proto = out.File
	file_protocli_bag_proto_goTypes = nil
	file_protocli_bag_proto_depIdxs = nil
}
