// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: base.proto

package gamelogic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 标准返回信息顶部
type ResultErr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrCode       int32                  `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"` //错误编号
	ErrText       string                 `protobuf:"bytes,2,opt,name=err_text,json=errText,proto3" json:"err_text,omitempty"`  //错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultErr) Reset() {
	*x = ResultErr{}
	mi := &file_base_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultErr) ProtoMessage() {}

func (x *ResultErr) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultErr.ProtoReflect.Descriptor instead.
func (*ResultErr) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{0}
}

func (x *ResultErr) GetErrCode() int32 {
	if x != nil {
		return x.ErrCode
	}
	return 0
}

func (x *ResultErr) GetErrText() string {
	if x != nil {
		return x.ErrText
	}
	return ""
}

type GameMoneyItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CfgId         int32                  `protobuf:"varint,1,opt,name=cfg_id,json=cfgId,proto3" json:"cfg_id,omitempty"` //配表编号
	Num           int64                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`                  //数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameMoneyItem) Reset() {
	*x = GameMoneyItem{}
	mi := &file_base_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameMoneyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameMoneyItem) ProtoMessage() {}

func (x *GameMoneyItem) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameMoneyItem.ProtoReflect.Descriptor instead.
func (*GameMoneyItem) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{1}
}

func (x *GameMoneyItem) GetCfgId() int32 {
	if x != nil {
		return x.CfgId
	}
	return 0
}

func (x *GameMoneyItem) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// 请求 获取游戏中的货币列表
type GetGameMoneyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameMoneyRequest) Reset() {
	*x = GetGameMoneyRequest{}
	mi := &file_base_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameMoneyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameMoneyRequest) ProtoMessage() {}

func (x *GetGameMoneyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameMoneyRequest.ProtoReflect.Descriptor instead.
func (*GetGameMoneyRequest) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{2}
}

// 响应 获取游戏中的货币列表
type GetGameMoneyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ResultErr             `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Data          []*GameMoneyItem       `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameMoneyResponse) Reset() {
	*x = GetGameMoneyResponse{}
	mi := &file_base_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameMoneyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameMoneyResponse) ProtoMessage() {}

func (x *GetGameMoneyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameMoneyResponse.ProtoReflect.Descriptor instead.
func (*GetGameMoneyResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameMoneyResponse) GetErr() *ResultErr {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetGameMoneyResponse) GetData() []*GameMoneyItem {
	if x != nil {
		return x.Data
	}
	return nil
}

// 同步 游戏中的货币改变
type SyncGameMoneyChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*GameMoneyItem       `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncGameMoneyChange) Reset() {
	*x = SyncGameMoneyChange{}
	mi := &file_base_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncGameMoneyChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncGameMoneyChange) ProtoMessage() {}

func (x *SyncGameMoneyChange) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncGameMoneyChange.ProtoReflect.Descriptor instead.
func (*SyncGameMoneyChange) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{4}
}

func (x *SyncGameMoneyChange) GetData() []*GameMoneyItem {
	if x != nil {
		return x.Data
	}
	return nil
}

// 基础消息结构
type Message struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Session        string                 `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`                                     // 会话ID
	MessageId      int32                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`               // 消息ID
	MessageContent []byte                 `protobuf:"bytes,3,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 消息内容
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_base_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *Message) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetMessageContent() []byte {
	if x != nil {
		return x.MessageContent
	}
	return nil
}

// 登录请求
type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // 角色名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_base_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{6}
}

func (x *LoginRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 登录响应
type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Role          *Role                  `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`        // 角色信息
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_base_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{7}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 角色信息
type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aid           string                 `protobuf:"bytes,1,opt,name=aid,proto3" json:"aid,omitempty"`                                                                            // 角色唯一编号
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                                                          // 角色名称
	Level         int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`                                                                       // 角色等级
	Gold          int32                  `protobuf:"varint,4,opt,name=gold,proto3" json:"gold,omitempty"`                                                                         // 金币
	Bag           map[string]int32       `protobuf:"bytes,5,rep,name=bag,proto3" json:"bag,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // 背包物品
	Heroes        []string               `protobuf:"bytes,6,rep,name=heroes,proto3" json:"heroes,omitempty"`                                                                      // 英雄列表
	Session       string                 `protobuf:"bytes,7,opt,name=session,proto3" json:"session,omitempty"`                                                                    // 会话ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_base_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{8}
}

func (x *Role) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Role) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *Role) GetBag() map[string]int32 {
	if x != nil {
		return x.Bag
	}
	return nil
}

func (x *Role) GetHeroes() []string {
	if x != nil {
		return x.Heroes
	}
	return nil
}

func (x *Role) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

// 获取角色信息请求
type GetRoleInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleInfoRequest) Reset() {
	*x = GetRoleInfoRequest{}
	mi := &file_base_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleInfoRequest) ProtoMessage() {}

func (x *GetRoleInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleInfoRequest.ProtoReflect.Descriptor instead.
func (*GetRoleInfoRequest) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{9}
}

// 获取角色信息响应
type GetRoleInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Role          *Role                  `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`        // 角色信息
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleInfoResponse) Reset() {
	*x = GetRoleInfoResponse{}
	mi := &file_base_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleInfoResponse) ProtoMessage() {}

func (x *GetRoleInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_base_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleInfoResponse.ProtoReflect.Descriptor instead.
func (*GetRoleInfoResponse) Descriptor() ([]byte, []int) {
	return file_base_proto_rawDescGZIP(), []int{10}
}

func (x *GetRoleInfoResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetRoleInfoResponse) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *GetRoleInfoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_base_proto protoreflect.FileDescriptor

const file_base_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"base.proto\x12\bprotocli\"A\n" +
	"\tResultErr\x12\x19\n" +
	"\berr_code\x18\x01 \x01(\x05R\aerrCode\x12\x19\n" +
	"\berr_text\x18\x02 \x01(\tR\aerrText\"8\n" +
	"\rGameMoneyItem\x12\x15\n" +
	"\x06cfg_id\x18\x01 \x01(\x05R\x05cfgId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x03R\x03num\"\x15\n" +
	"\x13GetGameMoneyRequest\"j\n" +
	"\x14GetGameMoneyResponse\x12%\n" +
	"\x03err\x18\x01 \x01(\v2\x13.protocli.ResultErrR\x03err\x12+\n" +
	"\x04data\x18\x02 \x03(\v2\x17.protocli.GameMoneyItemR\x04data\"B\n" +
	"\x13SyncGameMoneyChange\x12+\n" +
	"\x04data\x18\x01 \x03(\v2\x17.protocli.GameMoneyItemR\x04data\"k\n" +
	"\aMessage\x12\x18\n" +
	"\asession\x18\x01 \x01(\tR\asession\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x05R\tmessageId\x12'\n" +
	"\x0fmessage_content\x18\x03 \x01(\fR\x0emessageContent\"\"\n" +
	"\fLoginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"g\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\x04role\x18\x02 \x01(\v2\x0e.protocli.RoleR\x04role\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xeb\x01\n" +
	"\x04Role\x12\x10\n" +
	"\x03aid\x18\x01 \x01(\tR\x03aid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x12\n" +
	"\x04gold\x18\x04 \x01(\x05R\x04gold\x12)\n" +
	"\x03bag\x18\x05 \x03(\v2\x17.protocli.Role.BagEntryR\x03bag\x12\x16\n" +
	"\x06heroes\x18\x06 \x03(\tR\x06heroes\x12\x18\n" +
	"\asession\x18\a \x01(\tR\asession\x1a6\n" +
	"\bBagEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x14\n" +
	"\x12GetRoleInfoRequest\"m\n" +
	"\x13GetRoleInfoResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\"\n" +
	"\x04role\x18\x02 \x01(\v2\x0e.protocli.RoleR\x04role\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\x1bZ\x19zgame/pb/golang/gamelogicb\x06proto3"

var (
	file_base_proto_rawDescOnce sync.Once
	file_base_proto_rawDescData []byte
)

func file_base_proto_rawDescGZIP() []byte {
	file_base_proto_rawDescOnce.Do(func() {
		file_base_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)))
	})
	return file_base_proto_rawDescData
}

var file_base_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_base_proto_goTypes = []any{
	(*ResultErr)(nil),            // 0: protocli.ResultErr
	(*GameMoneyItem)(nil),        // 1: protocli.GameMoneyItem
	(*GetGameMoneyRequest)(nil),  // 2: protocli.GetGameMoneyRequest
	(*GetGameMoneyResponse)(nil), // 3: protocli.GetGameMoneyResponse
	(*SyncGameMoneyChange)(nil),  // 4: protocli.SyncGameMoneyChange
	(*Message)(nil),              // 5: protocli.Message
	(*LoginRequest)(nil),         // 6: protocli.LoginRequest
	(*LoginResponse)(nil),        // 7: protocli.LoginResponse
	(*Role)(nil),                 // 8: protocli.Role
	(*GetRoleInfoRequest)(nil),   // 9: protocli.GetRoleInfoRequest
	(*GetRoleInfoResponse)(nil),  // 10: protocli.GetRoleInfoResponse
	nil,                          // 11: protocli.Role.BagEntry
}
var file_base_proto_depIdxs = []int32{
	0,  // 0: protocli.GetGameMoneyResponse.err:type_name -> protocli.ResultErr
	1,  // 1: protocli.GetGameMoneyResponse.data:type_name -> protocli.GameMoneyItem
	1,  // 2: protocli.SyncGameMoneyChange.data:type_name -> protocli.GameMoneyItem
	8,  // 3: protocli.LoginResponse.role:type_name -> protocli.Role
	11, // 4: protocli.Role.bag:type_name -> protocli.Role.BagEntry
	8,  // 5: protocli.GetRoleInfoResponse.role:type_name -> protocli.Role
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_base_proto_init() }
func file_base_proto_init() {
	if File_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_base_proto_rawDesc), len(file_base_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_proto_goTypes,
		DependencyIndexes: file_base_proto_depIdxs,
		MessageInfos:      file_base_proto_msgTypes,
	}.Build()
	File_base_proto = out.File
	file_base_proto_goTypes = nil
	file_base_proto_depIdxs = nil
}
