// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: protocli/hero.proto

package golang

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 添加英雄请求
type AddHeroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeroId        string                 `protobuf:"bytes,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"` // 英雄ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHeroRequest) Reset() {
	*x = AddHeroRequest{}
	mi := &file_protocli_hero_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHeroRequest) ProtoMessage() {}

func (x *AddHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_hero_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHeroRequest.ProtoReflect.Descriptor instead.
func (*AddHeroRequest) Descriptor() ([]byte, []int) {
	return file_protocli_hero_proto_rawDescGZIP(), []int{0}
}

func (x *AddHeroRequest) GetHeroId() string {
	if x != nil {
		return x.HeroId
	}
	return ""
}

// 添加英雄响应
type AddHeroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddHeroResponse) Reset() {
	*x = AddHeroResponse{}
	mi := &file_protocli_hero_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddHeroResponse) ProtoMessage() {}

func (x *AddHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_hero_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddHeroResponse.ProtoReflect.Descriptor instead.
func (*AddHeroResponse) Descriptor() ([]byte, []int) {
	return file_protocli_hero_proto_rawDescGZIP(), []int{1}
}

func (x *AddHeroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddHeroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 移除英雄请求
type RemoveHeroRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HeroId        string                 `protobuf:"bytes,1,opt,name=hero_id,json=heroId,proto3" json:"hero_id,omitempty"` // 英雄ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveHeroRequest) Reset() {
	*x = RemoveHeroRequest{}
	mi := &file_protocli_hero_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHeroRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHeroRequest) ProtoMessage() {}

func (x *RemoveHeroRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_hero_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHeroRequest.ProtoReflect.Descriptor instead.
func (*RemoveHeroRequest) Descriptor() ([]byte, []int) {
	return file_protocli_hero_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveHeroRequest) GetHeroId() string {
	if x != nil {
		return x.HeroId
	}
	return ""
}

// 移除英雄响应
type RemoveHeroResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveHeroResponse) Reset() {
	*x = RemoveHeroResponse{}
	mi := &file_protocli_hero_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveHeroResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveHeroResponse) ProtoMessage() {}

func (x *RemoveHeroResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_hero_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveHeroResponse.ProtoReflect.Descriptor instead.
func (*RemoveHeroResponse) Descriptor() ([]byte, []int) {
	return file_protocli_hero_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveHeroResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveHeroResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 获取英雄列表请求
type GetHeroesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeroesRequest) Reset() {
	*x = GetHeroesRequest{}
	mi := &file_protocli_hero_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeroesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeroesRequest) ProtoMessage() {}

func (x *GetHeroesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_hero_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeroesRequest.ProtoReflect.Descriptor instead.
func (*GetHeroesRequest) Descriptor() ([]byte, []int) {
	return file_protocli_hero_proto_rawDescGZIP(), []int{4}
}

// 获取英雄列表响应
type GetHeroesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Heroes        []string               `protobuf:"bytes,2,rep,name=heroes,proto3" json:"heroes,omitempty"`    // 英雄列表
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeroesResponse) Reset() {
	*x = GetHeroesResponse{}
	mi := &file_protocli_hero_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeroesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeroesResponse) ProtoMessage() {}

func (x *GetHeroesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocli_hero_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeroesResponse.ProtoReflect.Descriptor instead.
func (*GetHeroesResponse) Descriptor() ([]byte, []int) {
	return file_protocli_hero_proto_rawDescGZIP(), []int{5}
}

func (x *GetHeroesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetHeroesResponse) GetHeroes() []string {
	if x != nil {
		return x.Heroes
	}
	return nil
}

func (x *GetHeroesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protocli_hero_proto protoreflect.FileDescriptor

const file_protocli_hero_proto_rawDesc = "" +
	"\n" +
	"\x13protocli/hero.proto\x12\bprotocli\")\n" +
	"\x0eAddHeroRequest\x12\x17\n" +
	"\ahero_id\x18\x01 \x01(\tR\x06heroId\"E\n" +
	"\x0fAddHeroResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\",\n" +
	"\x11RemoveHeroRequest\x12\x17\n" +
	"\ahero_id\x18\x01 \x01(\tR\x06heroId\"H\n" +
	"\x12RemoveHeroResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10GetHeroesRequest\"_\n" +
	"\x11GetHeroesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06heroes\x18\x02 \x03(\tR\x06heroes\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessageB\x11Z\x0fzgame/pb/golangb\x06proto3"

var (
	file_protocli_hero_proto_rawDescOnce sync.Once
	file_protocli_hero_proto_rawDescData []byte
)

func file_protocli_hero_proto_rawDescGZIP() []byte {
	file_protocli_hero_proto_rawDescOnce.Do(func() {
		file_protocli_hero_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocli_hero_proto_rawDesc), len(file_protocli_hero_proto_rawDesc)))
	})
	return file_protocli_hero_proto_rawDescData
}

var file_protocli_hero_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_protocli_hero_proto_goTypes = []any{
	(*AddHeroRequest)(nil),     // 0: protocli.AddHeroRequest
	(*AddHeroResponse)(nil),    // 1: protocli.AddHeroResponse
	(*RemoveHeroRequest)(nil),  // 2: protocli.RemoveHeroRequest
	(*RemoveHeroResponse)(nil), // 3: protocli.RemoveHeroResponse
	(*GetHeroesRequest)(nil),   // 4: protocli.GetHeroesRequest
	(*GetHeroesResponse)(nil),  // 5: protocli.GetHeroesResponse
}
var file_protocli_hero_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocli_hero_proto_init() }
func file_protocli_hero_proto_init() {
	if File_protocli_hero_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocli_hero_proto_rawDesc), len(file_protocli_hero_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocli_hero_proto_goTypes,
		DependencyIndexes: file_protocli_hero_proto_depIdxs,
		MessageInfos:      file_protocli_hero_proto_msgTypes,
	}.Build()
	File_protocli_hero_proto = out.File
	file_protocli_hero_proto_goTypes = nil
	file_protocli_hero_proto_depIdxs = nil
}
