// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType 消息类型枚举
type MessageType int32

const (
	MessageType_MSG_TYPE_UNKNOWN MessageType = 0
	// SSO Auth 协议 (1-100)
	MessageType_MSG_TYPE_AUTH_REGISTER MessageType = 1
	MessageType_MSG_TYPE_AUTH_LOGIN    MessageType = 2
	MessageType_MSG_TYPE_AUTH_VALIDATE MessageType = 3
	// Game Logic 协议 (101-200)
	MessageType_MSG_TYPE_GAME_CREATE_CHARACTER        MessageType = 101
	MessageType_MSG_TYPE_GAME_GET_CHARACTERS          MessageType = 102
	MessageType_MSG_TYPE_GAME_GET_CHARACTER           MessageType = 103
	MessageType_MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS MessageType = 104
	MessageType_MSG_TYPE_GAME_BATTLE                  MessageType = 105
	MessageType_MSG_TYPE_GAME_GET_BAG                 MessageType = 106
	// Bill 协议 (201-300)
	MessageType_MSG_TYPE_BILL_CREATE_PAYMENT        MessageType = 201
	MessageType_MSG_TYPE_BILL_GET_PAYMENT           MessageType = 202
	MessageType_MSG_TYPE_BILL_UPDATE_PAYMENT_STATUS MessageType = 203
	MessageType_MSG_TYPE_BILL_GET_USER_PAYMENTS     MessageType = 204
	// Chat 协议 (301-400)
	MessageType_MSG_TYPE_CHAT_SEND_MESSAGE          MessageType = 301
	MessageType_MSG_TYPE_CHAT_GET_MESSAGES          MessageType = 302
	MessageType_MSG_TYPE_CHAT_GET_CONVERSATIONS     MessageType = 303
	MessageType_MSG_TYPE_CHAT_UPDATE_MESSAGE_STATUS MessageType = 304
	// 响应消息
	MessageType_MSG_TYPE_RESPONSE MessageType = 999
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MSG_TYPE_UNKNOWN",
		1:   "MSG_TYPE_AUTH_REGISTER",
		2:   "MSG_TYPE_AUTH_LOGIN",
		3:   "MSG_TYPE_AUTH_VALIDATE",
		101: "MSG_TYPE_GAME_CREATE_CHARACTER",
		102: "MSG_TYPE_GAME_GET_CHARACTERS",
		103: "MSG_TYPE_GAME_GET_CHARACTER",
		104: "MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS",
		105: "MSG_TYPE_GAME_BATTLE",
		106: "MSG_TYPE_GAME_GET_BAG",
		201: "MSG_TYPE_BILL_CREATE_PAYMENT",
		202: "MSG_TYPE_BILL_GET_PAYMENT",
		203: "MSG_TYPE_BILL_UPDATE_PAYMENT_STATUS",
		204: "MSG_TYPE_BILL_GET_USER_PAYMENTS",
		301: "MSG_TYPE_CHAT_SEND_MESSAGE",
		302: "MSG_TYPE_CHAT_GET_MESSAGES",
		303: "MSG_TYPE_CHAT_GET_CONVERSATIONS",
		304: "MSG_TYPE_CHAT_UPDATE_MESSAGE_STATUS",
		999: "MSG_TYPE_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MSG_TYPE_UNKNOWN":                      0,
		"MSG_TYPE_AUTH_REGISTER":                1,
		"MSG_TYPE_AUTH_LOGIN":                   2,
		"MSG_TYPE_AUTH_VALIDATE":                3,
		"MSG_TYPE_GAME_CREATE_CHARACTER":        101,
		"MSG_TYPE_GAME_GET_CHARACTERS":          102,
		"MSG_TYPE_GAME_GET_CHARACTER":           103,
		"MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS": 104,
		"MSG_TYPE_GAME_BATTLE":                  105,
		"MSG_TYPE_GAME_GET_BAG":                 106,
		"MSG_TYPE_BILL_CREATE_PAYMENT":          201,
		"MSG_TYPE_BILL_GET_PAYMENT":             202,
		"MSG_TYPE_BILL_UPDATE_PAYMENT_STATUS":   203,
		"MSG_TYPE_BILL_GET_USER_PAYMENTS":       204,
		"MSG_TYPE_CHAT_SEND_MESSAGE":            301,
		"MSG_TYPE_CHAT_GET_MESSAGES":            302,
		"MSG_TYPE_CHAT_GET_CONVERSATIONS":       303,
		"MSG_TYPE_CHAT_UPDATE_MESSAGE_STATUS":   304,
		"MSG_TYPE_RESPONSE":                     999,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Message 通用消息包装器
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=proto.MessageType" json:"type,omitempty"` // 消息类型
	// Types that are valid to be assigned to Data:
	//
	//	*Message_AuthRegister
	//	*Message_AuthLogin
	//	*Message_AuthValidate
	//	*Message_GameCreateCharacter
	//	*Message_GameGetCharacters
	//	*Message_GameGetCharacter
	//	*Message_GameUpdateCharacterStatus
	//	*Message_GameBattle
	//	*Message_GameGetBag
	//	*Message_BillCreatePayment
	//	*Message_BillGetPayment
	//	*Message_BillUpdatePaymentStatus
	//	*Message_BillGetUserPayments
	//	*Message_ChatSendMessage
	//	*Message_ChatGetMessages
	//	*Message_ChatGetConversations
	//	*Message_ChatUpdateMessageStatus
	//	*Message_Response
	Data          isMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_TYPE_UNKNOWN
}

func (x *Message) GetData() isMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetAuthRegister() *AuthRegister {
	if x != nil {
		if x, ok := x.Data.(*Message_AuthRegister); ok {
			return x.AuthRegister
		}
	}
	return nil
}

func (x *Message) GetAuthLogin() *AuthLogin {
	if x != nil {
		if x, ok := x.Data.(*Message_AuthLogin); ok {
			return x.AuthLogin
		}
	}
	return nil
}

func (x *Message) GetAuthValidate() *AuthValidate {
	if x != nil {
		if x, ok := x.Data.(*Message_AuthValidate); ok {
			return x.AuthValidate
		}
	}
	return nil
}

func (x *Message) GetGameCreateCharacter() *GameCreateCharacter {
	if x != nil {
		if x, ok := x.Data.(*Message_GameCreateCharacter); ok {
			return x.GameCreateCharacter
		}
	}
	return nil
}

func (x *Message) GetGameGetCharacters() *GameGetCharacters {
	if x != nil {
		if x, ok := x.Data.(*Message_GameGetCharacters); ok {
			return x.GameGetCharacters
		}
	}
	return nil
}

func (x *Message) GetGameGetCharacter() *GameGetCharacter {
	if x != nil {
		if x, ok := x.Data.(*Message_GameGetCharacter); ok {
			return x.GameGetCharacter
		}
	}
	return nil
}

func (x *Message) GetGameUpdateCharacterStatus() *GameUpdateCharacterStatus {
	if x != nil {
		if x, ok := x.Data.(*Message_GameUpdateCharacterStatus); ok {
			return x.GameUpdateCharacterStatus
		}
	}
	return nil
}

func (x *Message) GetGameBattle() *GameBattle {
	if x != nil {
		if x, ok := x.Data.(*Message_GameBattle); ok {
			return x.GameBattle
		}
	}
	return nil
}

func (x *Message) GetGameGetBag() *GameGetBag {
	if x != nil {
		if x, ok := x.Data.(*Message_GameGetBag); ok {
			return x.GameGetBag
		}
	}
	return nil
}

func (x *Message) GetBillCreatePayment() *BillCreatePayment {
	if x != nil {
		if x, ok := x.Data.(*Message_BillCreatePayment); ok {
			return x.BillCreatePayment
		}
	}
	return nil
}

func (x *Message) GetBillGetPayment() *BillGetPayment {
	if x != nil {
		if x, ok := x.Data.(*Message_BillGetPayment); ok {
			return x.BillGetPayment
		}
	}
	return nil
}

func (x *Message) GetBillUpdatePaymentStatus() *BillUpdatePaymentStatus {
	if x != nil {
		if x, ok := x.Data.(*Message_BillUpdatePaymentStatus); ok {
			return x.BillUpdatePaymentStatus
		}
	}
	return nil
}

func (x *Message) GetBillGetUserPayments() *BillGetUserPayments {
	if x != nil {
		if x, ok := x.Data.(*Message_BillGetUserPayments); ok {
			return x.BillGetUserPayments
		}
	}
	return nil
}

func (x *Message) GetChatSendMessage() *ChatSendMessage {
	if x != nil {
		if x, ok := x.Data.(*Message_ChatSendMessage); ok {
			return x.ChatSendMessage
		}
	}
	return nil
}

func (x *Message) GetChatGetMessages() *ChatGetMessages {
	if x != nil {
		if x, ok := x.Data.(*Message_ChatGetMessages); ok {
			return x.ChatGetMessages
		}
	}
	return nil
}

func (x *Message) GetChatGetConversations() *ChatGetConversations {
	if x != nil {
		if x, ok := x.Data.(*Message_ChatGetConversations); ok {
			return x.ChatGetConversations
		}
	}
	return nil
}

func (x *Message) GetChatUpdateMessageStatus() *ChatUpdateMessageStatus {
	if x != nil {
		if x, ok := x.Data.(*Message_ChatUpdateMessageStatus); ok {
			return x.ChatUpdateMessageStatus
		}
	}
	return nil
}

func (x *Message) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Data.(*Message_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isMessage_Data interface {
	isMessage_Data()
}

type Message_AuthRegister struct {
	// Auth 消息
	AuthRegister *AuthRegister `protobuf:"bytes,101,opt,name=auth_register,json=authRegister,proto3,oneof"`
}

type Message_AuthLogin struct {
	AuthLogin *AuthLogin `protobuf:"bytes,102,opt,name=auth_login,json=authLogin,proto3,oneof"`
}

type Message_AuthValidate struct {
	AuthValidate *AuthValidate `protobuf:"bytes,103,opt,name=auth_validate,json=authValidate,proto3,oneof"`
}

type Message_GameCreateCharacter struct {
	// Game 消息
	GameCreateCharacter *GameCreateCharacter `protobuf:"bytes,201,opt,name=game_create_character,json=gameCreateCharacter,proto3,oneof"`
}

type Message_GameGetCharacters struct {
	GameGetCharacters *GameGetCharacters `protobuf:"bytes,202,opt,name=game_get_characters,json=gameGetCharacters,proto3,oneof"`
}

type Message_GameGetCharacter struct {
	GameGetCharacter *GameGetCharacter `protobuf:"bytes,203,opt,name=game_get_character,json=gameGetCharacter,proto3,oneof"`
}

type Message_GameUpdateCharacterStatus struct {
	GameUpdateCharacterStatus *GameUpdateCharacterStatus `protobuf:"bytes,204,opt,name=game_update_character_status,json=gameUpdateCharacterStatus,proto3,oneof"`
}

type Message_GameBattle struct {
	GameBattle *GameBattle `protobuf:"bytes,205,opt,name=game_battle,json=gameBattle,proto3,oneof"`
}

type Message_GameGetBag struct {
	GameGetBag *GameGetBag `protobuf:"bytes,206,opt,name=game_get_bag,json=gameGetBag,proto3,oneof"`
}

type Message_BillCreatePayment struct {
	// Bill 消息
	BillCreatePayment *BillCreatePayment `protobuf:"bytes,301,opt,name=bill_create_payment,json=billCreatePayment,proto3,oneof"`
}

type Message_BillGetPayment struct {
	BillGetPayment *BillGetPayment `protobuf:"bytes,302,opt,name=bill_get_payment,json=billGetPayment,proto3,oneof"`
}

type Message_BillUpdatePaymentStatus struct {
	BillUpdatePaymentStatus *BillUpdatePaymentStatus `protobuf:"bytes,303,opt,name=bill_update_payment_status,json=billUpdatePaymentStatus,proto3,oneof"`
}

type Message_BillGetUserPayments struct {
	BillGetUserPayments *BillGetUserPayments `protobuf:"bytes,304,opt,name=bill_get_user_payments,json=billGetUserPayments,proto3,oneof"`
}

type Message_ChatSendMessage struct {
	// Chat 消息
	ChatSendMessage *ChatSendMessage `protobuf:"bytes,401,opt,name=chat_send_message,json=chatSendMessage,proto3,oneof"`
}

type Message_ChatGetMessages struct {
	ChatGetMessages *ChatGetMessages `protobuf:"bytes,402,opt,name=chat_get_messages,json=chatGetMessages,proto3,oneof"`
}

type Message_ChatGetConversations struct {
	ChatGetConversations *ChatGetConversations `protobuf:"bytes,403,opt,name=chat_get_conversations,json=chatGetConversations,proto3,oneof"`
}

type Message_ChatUpdateMessageStatus struct {
	ChatUpdateMessageStatus *ChatUpdateMessageStatus `protobuf:"bytes,404,opt,name=chat_update_message_status,json=chatUpdateMessageStatus,proto3,oneof"`
}

type Message_Response struct {
	// 响应消息
	Response *Response `protobuf:"bytes,999,opt,name=response,proto3,oneof"`
}

func (*Message_AuthRegister) isMessage_Data() {}

func (*Message_AuthLogin) isMessage_Data() {}

func (*Message_AuthValidate) isMessage_Data() {}

func (*Message_GameCreateCharacter) isMessage_Data() {}

func (*Message_GameGetCharacters) isMessage_Data() {}

func (*Message_GameGetCharacter) isMessage_Data() {}

func (*Message_GameUpdateCharacterStatus) isMessage_Data() {}

func (*Message_GameBattle) isMessage_Data() {}

func (*Message_GameGetBag) isMessage_Data() {}

func (*Message_BillCreatePayment) isMessage_Data() {}

func (*Message_BillGetPayment) isMessage_Data() {}

func (*Message_BillUpdatePaymentStatus) isMessage_Data() {}

func (*Message_BillGetUserPayments) isMessage_Data() {}

func (*Message_ChatSendMessage) isMessage_Data() {}

func (*Message_ChatGetMessages) isMessage_Data() {}

func (*Message_ChatGetConversations) isMessage_Data() {}

func (*Message_ChatUpdateMessageStatus) isMessage_Data() {}

func (*Message_Response) isMessage_Data() {}

// Auth 消息
type AuthRegister struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegister) Reset() {
	*x = AuthRegister{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegister) ProtoMessage() {}

func (x *AuthRegister) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegister.ProtoReflect.Descriptor instead.
func (*AuthRegister) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRegister) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRegister) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRegister) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRegister) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type AuthLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLogin) Reset() {
	*x = AuthLogin{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLogin) ProtoMessage() {}

func (x *AuthLogin) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLogin.ProtoReflect.Descriptor instead.
func (*AuthLogin) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *AuthLogin) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthLogin) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthValidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthValidate) Reset() {
	*x = AuthValidate{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthValidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthValidate) ProtoMessage() {}

func (x *AuthValidate) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthValidate.ProtoReflect.Descriptor instead.
func (*AuthValidate) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *AuthValidate) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// Game 消息
type GameCreateCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCreateCharacter) Reset() {
	*x = GameCreateCharacter{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCreateCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCreateCharacter) ProtoMessage() {}

func (x *GameCreateCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCreateCharacter.ProtoReflect.Descriptor instead.
func (*GameCreateCharacter) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *GameCreateCharacter) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GameCreateCharacter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GameGetCharacters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameGetCharacters) Reset() {
	*x = GameGetCharacters{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameGetCharacters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetCharacters) ProtoMessage() {}

func (x *GameGetCharacters) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetCharacters.ProtoReflect.Descriptor instead.
func (*GameGetCharacters) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *GameGetCharacters) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GameGetCharacter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameGetCharacter) Reset() {
	*x = GameGetCharacter{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameGetCharacter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetCharacter) ProtoMessage() {}

func (x *GameGetCharacter) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetCharacter.ProtoReflect.Descriptor instead.
func (*GameGetCharacter) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *GameGetCharacter) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

type GameUpdateCharacterStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameUpdateCharacterStatus) Reset() {
	*x = GameUpdateCharacterStatus{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUpdateCharacterStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdateCharacterStatus) ProtoMessage() {}

func (x *GameUpdateCharacterStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdateCharacterStatus.ProtoReflect.Descriptor instead.
func (*GameUpdateCharacterStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *GameUpdateCharacterStatus) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *GameUpdateCharacterStatus) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GameBattle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	EnemyLevel    int32                  `protobuf:"varint,2,opt,name=enemy_level,json=enemyLevel,proto3" json:"enemy_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBattle) Reset() {
	*x = GameBattle{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBattle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBattle) ProtoMessage() {}

func (x *GameBattle) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBattle.ProtoReflect.Descriptor instead.
func (*GameBattle) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *GameBattle) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *GameBattle) GetEnemyLevel() int32 {
	if x != nil {
		return x.EnemyLevel
	}
	return 0
}

type GameGetBag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameGetBag) Reset() {
	*x = GameGetBag{}
	mi := &file_common_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameGetBag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetBag) ProtoMessage() {}

func (x *GameGetBag) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetBag.ProtoReflect.Descriptor instead.
func (*GameGetBag) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{9}
}

func (x *GameGetBag) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// Bill 消息
type BillCreatePayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillCreatePayment) Reset() {
	*x = BillCreatePayment{}
	mi := &file_common_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillCreatePayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillCreatePayment) ProtoMessage() {}

func (x *BillCreatePayment) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillCreatePayment.ProtoReflect.Descriptor instead.
func (*BillCreatePayment) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{10}
}

func (x *BillCreatePayment) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BillCreatePayment) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *BillCreatePayment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *BillCreatePayment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type BillGetPayment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint32                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillGetPayment) Reset() {
	*x = BillGetPayment{}
	mi := &file_common_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillGetPayment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillGetPayment) ProtoMessage() {}

func (x *BillGetPayment) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillGetPayment.ProtoReflect.Descriptor instead.
func (*BillGetPayment) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{11}
}

func (x *BillGetPayment) GetPaymentId() uint32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

type BillUpdatePaymentStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint32                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillUpdatePaymentStatus) Reset() {
	*x = BillUpdatePaymentStatus{}
	mi := &file_common_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillUpdatePaymentStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillUpdatePaymentStatus) ProtoMessage() {}

func (x *BillUpdatePaymentStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillUpdatePaymentStatus.ProtoReflect.Descriptor instead.
func (*BillUpdatePaymentStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{12}
}

func (x *BillUpdatePaymentStatus) GetPaymentId() uint32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *BillUpdatePaymentStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type BillGetUserPayments struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillGetUserPayments) Reset() {
	*x = BillGetUserPayments{}
	mi := &file_common_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillGetUserPayments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillGetUserPayments) ProtoMessage() {}

func (x *BillGetUserPayments) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillGetUserPayments.ProtoReflect.Descriptor instead.
func (*BillGetUserPayments) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{13}
}

func (x *BillGetUserPayments) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BillGetUserPayments) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *BillGetUserPayments) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Chat 消息
type ChatSendMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      uint32                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId    uint32                 `protobuf:"varint,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatSendMessage) Reset() {
	*x = ChatSendMessage{}
	mi := &file_common_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatSendMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatSendMessage) ProtoMessage() {}

func (x *ChatSendMessage) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatSendMessage.ProtoReflect.Descriptor instead.
func (*ChatSendMessage) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{14}
}

func (x *ChatSendMessage) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *ChatSendMessage) GetReceiverId() uint32 {
	if x != nil {
		return x.ReceiverId
	}
	return 0
}

func (x *ChatSendMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatSendMessage) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ChatGetMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OtherUserId   uint32                 `protobuf:"varint,2,opt,name=other_user_id,json=otherUserId,proto3" json:"other_user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatGetMessages) Reset() {
	*x = ChatGetMessages{}
	mi := &file_common_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatGetMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatGetMessages) ProtoMessage() {}

func (x *ChatGetMessages) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatGetMessages.ProtoReflect.Descriptor instead.
func (*ChatGetMessages) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{15}
}

func (x *ChatGetMessages) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ChatGetMessages) GetOtherUserId() uint32 {
	if x != nil {
		return x.OtherUserId
	}
	return 0
}

func (x *ChatGetMessages) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ChatGetMessages) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ChatGetConversations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatGetConversations) Reset() {
	*x = ChatGetConversations{}
	mi := &file_common_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatGetConversations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatGetConversations) ProtoMessage() {}

func (x *ChatGetConversations) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatGetConversations.ProtoReflect.Descriptor instead.
func (*ChatGetConversations) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{16}
}

func (x *ChatGetConversations) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ChatUpdateMessageStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint32                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUpdateMessageStatus) Reset() {
	*x = ChatUpdateMessageStatus{}
	mi := &file_common_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUpdateMessageStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUpdateMessageStatus) ProtoMessage() {}

func (x *ChatUpdateMessageStatus) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUpdateMessageStatus.ProtoReflect.Descriptor instead.
func (*ChatUpdateMessageStatus) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{17}
}

func (x *ChatUpdateMessageStatus) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ChatUpdateMessageStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// 响应消息
type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Response_AuthResponse
	//	*Response_GameResponse
	//	*Response_BillResponse
	//	*Response_ChatResponse
	Data          isResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_common_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{18}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() isResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *Response) GetGameResponse() *GameResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_GameResponse); ok {
			return x.GameResponse
		}
	}
	return nil
}

func (x *Response) GetBillResponse() *BillResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_BillResponse); ok {
			return x.BillResponse
		}
	}
	return nil
}

func (x *Response) GetChatResponse() *ChatResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_ChatResponse); ok {
			return x.ChatResponse
		}
	}
	return nil
}

type isResponse_Data interface {
	isResponse_Data()
}

type Response_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,101,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type Response_GameResponse struct {
	GameResponse *GameResponse `protobuf:"bytes,201,opt,name=game_response,json=gameResponse,proto3,oneof"`
}

type Response_BillResponse struct {
	BillResponse *BillResponse `protobuf:"bytes,301,opt,name=bill_response,json=billResponse,proto3,oneof"`
}

type Response_ChatResponse struct {
	ChatResponse *ChatResponse `protobuf:"bytes,401,opt,name=chat_response,json=chatResponse,proto3,oneof"`
}

func (*Response_AuthResponse) isResponse_Data() {}

func (*Response_GameResponse) isResponse_Data() {}

func (*Response_BillResponse) isResponse_Data() {}

func (*Response_ChatResponse) isResponse_Data() {}

// 具体响应消息
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_common_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{19}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*GameResponse_Character
	//	*GameResponse_Characters
	//	*GameResponse_BattleResult
	//	*GameResponse_BagItems
	Data          isGameResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameResponse) Reset() {
	*x = GameResponse{}
	mi := &file_common_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameResponse) ProtoMessage() {}

func (x *GameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameResponse.ProtoReflect.Descriptor instead.
func (*GameResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{20}
}

func (x *GameResponse) GetData() isGameResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GameResponse) GetCharacter() *Character {
	if x != nil {
		if x, ok := x.Data.(*GameResponse_Character); ok {
			return x.Character
		}
	}
	return nil
}

func (x *GameResponse) GetCharacters() *CharacterList {
	if x != nil {
		if x, ok := x.Data.(*GameResponse_Characters); ok {
			return x.Characters
		}
	}
	return nil
}

func (x *GameResponse) GetBattleResult() *BattleResult {
	if x != nil {
		if x, ok := x.Data.(*GameResponse_BattleResult); ok {
			return x.BattleResult
		}
	}
	return nil
}

func (x *GameResponse) GetBagItems() *BagItemList {
	if x != nil {
		if x, ok := x.Data.(*GameResponse_BagItems); ok {
			return x.BagItems
		}
	}
	return nil
}

type isGameResponse_Data interface {
	isGameResponse_Data()
}

type GameResponse_Character struct {
	Character *Character `protobuf:"bytes,1,opt,name=character,proto3,oneof"`
}

type GameResponse_Characters struct {
	Characters *CharacterList `protobuf:"bytes,2,opt,name=characters,proto3,oneof"`
}

type GameResponse_BattleResult struct {
	BattleResult *BattleResult `protobuf:"bytes,3,opt,name=battle_result,json=battleResult,proto3,oneof"`
}

type GameResponse_BagItems struct {
	BagItems *BagItemList `protobuf:"bytes,4,opt,name=bag_items,json=bagItems,proto3,oneof"`
}

func (*GameResponse_Character) isGameResponse_Data() {}

func (*GameResponse_Characters) isGameResponse_Data() {}

func (*GameResponse_BattleResult) isGameResponse_Data() {}

func (*GameResponse_BagItems) isGameResponse_Data() {}

type BillResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*BillResponse_Payment
	//	*BillResponse_Payments
	//	*BillResponse_Total
	Data          isBillResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillResponse) Reset() {
	*x = BillResponse{}
	mi := &file_common_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillResponse) ProtoMessage() {}

func (x *BillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillResponse.ProtoReflect.Descriptor instead.
func (*BillResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{21}
}

func (x *BillResponse) GetData() isBillResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *BillResponse) GetPayment() *Payment {
	if x != nil {
		if x, ok := x.Data.(*BillResponse_Payment); ok {
			return x.Payment
		}
	}
	return nil
}

func (x *BillResponse) GetPayments() *PaymentList {
	if x != nil {
		if x, ok := x.Data.(*BillResponse_Payments); ok {
			return x.Payments
		}
	}
	return nil
}

func (x *BillResponse) GetTotal() int32 {
	if x != nil {
		if x, ok := x.Data.(*BillResponse_Total); ok {
			return x.Total
		}
	}
	return 0
}

type isBillResponse_Data interface {
	isBillResponse_Data()
}

type BillResponse_Payment struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3,oneof"`
}

type BillResponse_Payments struct {
	Payments *PaymentList `protobuf:"bytes,2,opt,name=payments,proto3,oneof"`
}

type BillResponse_Total struct {
	Total int32 `protobuf:"varint,3,opt,name=total,proto3,oneof"`
}

func (*BillResponse_Payment) isBillResponse_Data() {}

func (*BillResponse_Payments) isBillResponse_Data() {}

func (*BillResponse_Total) isBillResponse_Data() {}

type ChatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ChatResponse_ChatMessage
	//	*ChatResponse_ChatMessages
	//	*ChatResponse_Conversations
	Data          isChatResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_common_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{22}
}

func (x *ChatResponse) GetData() isChatResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ChatResponse) GetChatMessage() *Message {
	if x != nil {
		if x, ok := x.Data.(*ChatResponse_ChatMessage); ok {
			return x.ChatMessage
		}
	}
	return nil
}

func (x *ChatResponse) GetChatMessages() *MessageList {
	if x != nil {
		if x, ok := x.Data.(*ChatResponse_ChatMessages); ok {
			return x.ChatMessages
		}
	}
	return nil
}

func (x *ChatResponse) GetConversations() *ConversationList {
	if x != nil {
		if x, ok := x.Data.(*ChatResponse_Conversations); ok {
			return x.Conversations
		}
	}
	return nil
}

type isChatResponse_Data interface {
	isChatResponse_Data()
}

type ChatResponse_ChatMessage struct {
	ChatMessage *Message `protobuf:"bytes,1,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type ChatResponse_ChatMessages struct {
	ChatMessages *MessageList `protobuf:"bytes,2,opt,name=chat_messages,json=chatMessages,proto3,oneof"`
}

type ChatResponse_Conversations struct {
	Conversations *ConversationList `protobuf:"bytes,3,opt,name=conversations,proto3,oneof"`
}

func (*ChatResponse_ChatMessage) isChatResponse_Data() {}

func (*ChatResponse_ChatMessages) isChatResponse_Data() {}

func (*ChatResponse_Conversations) isChatResponse_Data() {}

// 列表包装器
type CharacterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Character           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterList) Reset() {
	*x = CharacterList{}
	mi := &file_common_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterList) ProtoMessage() {}

func (x *CharacterList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterList.ProtoReflect.Descriptor instead.
func (*CharacterList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{23}
}

func (x *CharacterList) GetItems() []*Character {
	if x != nil {
		return x.Items
	}
	return nil
}

type BagItemList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BagItemData         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItemList) Reset() {
	*x = BagItemList{}
	mi := &file_common_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItemList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemList) ProtoMessage() {}

func (x *BagItemList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemList.ProtoReflect.Descriptor instead.
func (*BagItemList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{24}
}

func (x *BagItemList) GetItems() []*BagItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

type PaymentList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Payment             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentList) Reset() {
	*x = PaymentList{}
	mi := &file_common_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentList) ProtoMessage() {}

func (x *PaymentList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentList.ProtoReflect.Descriptor instead.
func (*PaymentList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{25}
}

func (x *PaymentList) GetItems() []*Payment {
	if x != nil {
		return x.Items
	}
	return nil
}

type MessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Message             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageList) Reset() {
	*x = MessageList{}
	mi := &file_common_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageList) ProtoMessage() {}

func (x *MessageList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageList.ProtoReflect.Descriptor instead.
func (*MessageList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{26}
}

func (x *MessageList) GetItems() []*Message {
	if x != nil {
		return x.Items
	}
	return nil
}

type ConversationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Conversation        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConversationList) Reset() {
	*x = ConversationList{}
	mi := &file_common_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationList) ProtoMessage() {}

func (x *ConversationList) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationList.ProtoReflect.Descriptor instead.
func (*ConversationList) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{27}
}

func (x *ConversationList) GetItems() []*Conversation {
	if x != nil {
		return x.Items
	}
	return nil
}

// 引用其他proto文件中的消息结构
type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int32                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Hp            int32                  `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            int32                  `protobuf:"varint,7,opt,name=mp,proto3" json:"mp,omitempty"`
	Strength      int32                  `protobuf:"varint,8,opt,name=strength,proto3" json:"strength,omitempty"`
	Agility       int32                  `protobuf:"varint,9,opt,name=agility,proto3" json:"agility,omitempty"`
	Intelligence  int32                  `protobuf:"varint,10,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Gold          int32                  `protobuf:"varint,11,opt,name=gold,proto3" json:"gold,omitempty"`
	Status        int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_common_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{28}
}

func (x *Character) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Character) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Character) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Character) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *Character) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Character) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *Character) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Character) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *Character) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type BattleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Victory       bool                   `protobuf:"varint,1,opt,name=victory,proto3" json:"victory,omitempty"`
	ExpGained     int32                  `protobuf:"varint,2,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`
	GoldGained    int32                  `protobuf:"varint,3,opt,name=gold_gained,json=goldGained,proto3" json:"gold_gained,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResult) Reset() {
	*x = BattleResult{}
	mi := &file_common_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResult) ProtoMessage() {}

func (x *BattleResult) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResult.ProtoReflect.Descriptor instead.
func (*BattleResult) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{29}
}

func (x *BattleResult) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *BattleResult) GetExpGained() int32 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

func (x *BattleResult) GetGoldGained() int32 {
	if x != nil {
		return x.GoldGained
	}
	return 0
}

func (x *BattleResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type BagItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemCfgId     int32                  `protobuf:"varint,2,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItemData) Reset() {
	*x = BagItemData{}
	mi := &file_common_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemData) ProtoMessage() {}

func (x *BagItemData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemData.ProtoReflect.Descriptor instead.
func (*BagItemData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{30}
}

func (x *BagItemData) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BagItemData) GetItemCfgId() int32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *BagItemData) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_common_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{31}
}

func (x *Payment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Payment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Payment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type Conversation struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserIds         []uint32               `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	LastMessage     string                 `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	LastMessageTime int64                  `protobuf:"varint,4,opt,name=last_message_time,json=lastMessageTime,proto3" json:"last_message_time,omitempty"`
	UnreadCount     int32                  `protobuf:"varint,5,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	CreatedAt       int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Conversation) Reset() {
	*x = Conversation{}
	mi := &file_common_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conversation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conversation) ProtoMessage() {}

func (x *Conversation) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conversation.ProtoReflect.Descriptor instead.
func (*Conversation) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{32}
}

func (x *Conversation) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Conversation) GetUserIds() []uint32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Conversation) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

func (x *Conversation) GetLastMessageTime() int64 {
	if x != nil {
		return x.LastMessageTime
	}
	return 0
}

func (x *Conversation) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *Conversation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Conversation) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\x05proto\"\xdc\n" +
	"\n" +
	"\aMessage\x12&\n" +
	"\x04type\x18\x01 \x01(\x0e2\x12.proto.MessageTypeR\x04type\x12:\n" +
	"\rauth_register\x18e \x01(\v2\x13.proto.AuthRegisterH\x00R\fauthRegister\x121\n" +
	"\n" +
	"auth_login\x18f \x01(\v2\x10.proto.AuthLoginH\x00R\tauthLogin\x12:\n" +
	"\rauth_validate\x18g \x01(\v2\x13.proto.AuthValidateH\x00R\fauthValidate\x12Q\n" +
	"\x15game_create_character\x18\xc9\x01 \x01(\v2\x1a.proto.GameCreateCharacterH\x00R\x13gameCreateCharacter\x12K\n" +
	"\x13game_get_characters\x18\xca\x01 \x01(\v2\x18.proto.GameGetCharactersH\x00R\x11gameGetCharacters\x12H\n" +
	"\x12game_get_character\x18\xcb\x01 \x01(\v2\x17.proto.GameGetCharacterH\x00R\x10gameGetCharacter\x12d\n" +
	"\x1cgame_update_character_status\x18\xcc\x01 \x01(\v2 .proto.GameUpdateCharacterStatusH\x00R\x19gameUpdateCharacterStatus\x125\n" +
	"\vgame_battle\x18\xcd\x01 \x01(\v2\x11.proto.GameBattleH\x00R\n" +
	"gameBattle\x126\n" +
	"\fgame_get_bag\x18\xce\x01 \x01(\v2\x11.proto.GameGetBagH\x00R\n" +
	"gameGetBag\x12K\n" +
	"\x13bill_create_payment\x18\xad\x02 \x01(\v2\x18.proto.BillCreatePaymentH\x00R\x11billCreatePayment\x12B\n" +
	"\x10bill_get_payment\x18\xae\x02 \x01(\v2\x15.proto.BillGetPaymentH\x00R\x0ebillGetPayment\x12^\n" +
	"\x1abill_update_payment_status\x18\xaf\x02 \x01(\v2\x1e.proto.BillUpdatePaymentStatusH\x00R\x17billUpdatePaymentStatus\x12R\n" +
	"\x16bill_get_user_payments\x18\xb0\x02 \x01(\v2\x1a.proto.BillGetUserPaymentsH\x00R\x13billGetUserPayments\x12E\n" +
	"\x11chat_send_message\x18\x91\x03 \x01(\v2\x16.proto.ChatSendMessageH\x00R\x0fchatSendMessage\x12E\n" +
	"\x11chat_get_messages\x18\x92\x03 \x01(\v2\x16.proto.ChatGetMessagesH\x00R\x0fchatGetMessages\x12T\n" +
	"\x16chat_get_conversations\x18\x93\x03 \x01(\v2\x1b.proto.ChatGetConversationsH\x00R\x14chatGetConversations\x12^\n" +
	"\x1achat_update_message_status\x18\x94\x03 \x01(\v2\x1e.proto.ChatUpdateMessageStatusH\x00R\x17chatUpdateMessageStatus\x12.\n" +
	"\bresponse\x18\xe7\a \x01(\v2\x0f.proto.ResponseH\x00R\bresponseB\x06\n" +
	"\x04data\"x\n" +
	"\fAuthRegister\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"C\n" +
	"\tAuthLogin\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"$\n" +
	"\fAuthValidate\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"B\n" +
	"\x13GameCreateCharacter\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x11GameGetCharacters\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"5\n" +
	"\x10GameGetCharacter\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\"V\n" +
	"\x19GameUpdateCharacterStatus\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"P\n" +
	"\n" +
	"GameBattle\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x1f\n" +
	"\venemy_level\x18\x02 \x01(\x05R\n" +
	"enemyLevel\"%\n" +
	"\n" +
	"GameGetBag\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"\x8a\x01\n" +
	"\x11BillCreatePayment\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\"/\n" +
	"\x0eBillGetPayment\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\rR\tpaymentId\"P\n" +
	"\x17BillUpdatePaymentStatus\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\rR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"_\n" +
	"\x13BillGetUserPayments\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"}\n" +
	"\x0fChatSendMessage\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\rR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x02 \x01(\rR\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"|\n" +
	"\x0fChatGetMessages\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\"\n" +
	"\rother_user_id\x18\x02 \x01(\rR\votherUserId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"/\n" +
	"\x14ChatGetConversations\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"P\n" +
	"\x17ChatUpdateMessageStatus\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xb3\x02\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\rauth_response\x18e \x01(\v2\x13.proto.AuthResponseH\x00R\fauthResponse\x12;\n" +
	"\rgame_response\x18\xc9\x01 \x01(\v2\x13.proto.GameResponseH\x00R\fgameResponse\x12;\n" +
	"\rbill_response\x18\xad\x02 \x01(\v2\x13.proto.BillResponseH\x00R\fbillResponse\x12;\n" +
	"\rchat_response\x18\x91\x03 \x01(\v2\x13.proto.ChatResponseH\x00R\fchatResponseB\x06\n" +
	"\x04data\"u\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\xef\x01\n" +
	"\fGameResponse\x120\n" +
	"\tcharacter\x18\x01 \x01(\v2\x10.proto.CharacterH\x00R\tcharacter\x126\n" +
	"\n" +
	"characters\x18\x02 \x01(\v2\x14.proto.CharacterListH\x00R\n" +
	"characters\x12:\n" +
	"\rbattle_result\x18\x03 \x01(\v2\x13.proto.BattleResultH\x00R\fbattleResult\x121\n" +
	"\tbag_items\x18\x04 \x01(\v2\x12.proto.BagItemListH\x00R\bbagItemsB\x06\n" +
	"\x04data\"\x8c\x01\n" +
	"\fBillResponse\x12*\n" +
	"\apayment\x18\x01 \x01(\v2\x0e.proto.PaymentH\x00R\apayment\x120\n" +
	"\bpayments\x18\x02 \x01(\v2\x12.proto.PaymentListH\x00R\bpayments\x12\x16\n" +
	"\x05total\x18\x03 \x01(\x05H\x00R\x05totalB\x06\n" +
	"\x04data\"\xc7\x01\n" +
	"\fChatResponse\x123\n" +
	"\fchat_message\x18\x01 \x01(\v2\x0e.proto.MessageH\x00R\vchatMessage\x129\n" +
	"\rchat_messages\x18\x02 \x01(\v2\x12.proto.MessageListH\x00R\fchatMessages\x12?\n" +
	"\rconversations\x18\x03 \x01(\v2\x17.proto.ConversationListH\x00R\rconversationsB\x06\n" +
	"\x04data\"7\n" +
	"\rCharacterList\x12&\n" +
	"\x05items\x18\x01 \x03(\v2\x10.proto.CharacterR\x05items\"7\n" +
	"\vBagItemList\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.proto.BagItemDataR\x05items\"3\n" +
	"\vPaymentList\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.proto.PaymentR\x05items\"3\n" +
	"\vMessageList\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.proto.MessageR\x05items\"=\n" +
	"\x10ConversationList\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.proto.ConversationR\x05items\"\x96\x02\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x05R\x03exp\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\x05R\x02hp\x12\x0e\n" +
	"\x02mp\x18\a \x01(\x05R\x02mp\x12\x1a\n" +
	"\bstrength\x18\b \x01(\x05R\bstrength\x12\x18\n" +
	"\aagility\x18\t \x01(\x05R\aagility\x12\"\n" +
	"\fintelligence\x18\n" +
	" \x01(\x05R\fintelligence\x12\x12\n" +
	"\x04gold\x18\v \x01(\x05R\x04gold\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status\"\x82\x01\n" +
	"\fBattleResult\x12\x18\n" +
	"\avictory\x18\x01 \x01(\bR\avictory\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\x02 \x01(\x05R\texpGained\x12\x1f\n" +
	"\vgold_gained\x18\x03 \x01(\x05R\n" +
	"goldGained\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"X\n" +
	"\vBagItemData\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1e\n" +
	"\vitem_cfg_id\x18\x02 \x01(\x05R\titemCfgId\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\"\x8d\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"\xe9\x01\n" +
	"\fConversation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\rR\auserIds\x12!\n" +
	"\flast_message\x18\x03 \x01(\tR\vlastMessage\x12*\n" +
	"\x11last_message_time\x18\x04 \x01(\x03R\x0flastMessageTime\x12!\n" +
	"\funread_count\x18\x05 \x01(\x05R\vunreadCount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt*\xf8\x04\n" +
	"\vMessageType\x12\x14\n" +
	"\x10MSG_TYPE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16MSG_TYPE_AUTH_REGISTER\x10\x01\x12\x17\n" +
	"\x13MSG_TYPE_AUTH_LOGIN\x10\x02\x12\x1a\n" +
	"\x16MSG_TYPE_AUTH_VALIDATE\x10\x03\x12\"\n" +
	"\x1eMSG_TYPE_GAME_CREATE_CHARACTER\x10e\x12 \n" +
	"\x1cMSG_TYPE_GAME_GET_CHARACTERS\x10f\x12\x1f\n" +
	"\x1bMSG_TYPE_GAME_GET_CHARACTER\x10g\x12)\n" +
	"%MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS\x10h\x12\x18\n" +
	"\x14MSG_TYPE_GAME_BATTLE\x10i\x12\x19\n" +
	"\x15MSG_TYPE_GAME_GET_BAG\x10j\x12!\n" +
	"\x1cMSG_TYPE_BILL_CREATE_PAYMENT\x10\xc9\x01\x12\x1e\n" +
	"\x19MSG_TYPE_BILL_GET_PAYMENT\x10\xca\x01\x12(\n" +
	"#MSG_TYPE_BILL_UPDATE_PAYMENT_STATUS\x10\xcb\x01\x12$\n" +
	"\x1fMSG_TYPE_BILL_GET_USER_PAYMENTS\x10\xcc\x01\x12\x1f\n" +
	"\x1aMSG_TYPE_CHAT_SEND_MESSAGE\x10\xad\x02\x12\x1f\n" +
	"\x1aMSG_TYPE_CHAT_GET_MESSAGES\x10\xae\x02\x12$\n" +
	"\x1fMSG_TYPE_CHAT_GET_CONVERSATIONS\x10\xaf\x02\x12(\n" +
	"#MSG_TYPE_CHAT_UPDATE_MESSAGE_STATUS\x10\xb0\x02\x12\x16\n" +
	"\x11MSG_TYPE_RESPONSE\x10\xe7\aB\x1eZ\x1cgithub.com/aoyo/qp/pkg/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_common_proto_goTypes = []any{
	(MessageType)(0),                  // 0: proto.MessageType
	(*Message)(nil),                   // 1: proto.Message
	(*AuthRegister)(nil),              // 2: proto.AuthRegister
	(*AuthLogin)(nil),                 // 3: proto.AuthLogin
	(*AuthValidate)(nil),              // 4: proto.AuthValidate
	(*GameCreateCharacter)(nil),       // 5: proto.GameCreateCharacter
	(*GameGetCharacters)(nil),         // 6: proto.GameGetCharacters
	(*GameGetCharacter)(nil),          // 7: proto.GameGetCharacter
	(*GameUpdateCharacterStatus)(nil), // 8: proto.GameUpdateCharacterStatus
	(*GameBattle)(nil),                // 9: proto.GameBattle
	(*GameGetBag)(nil),                // 10: proto.GameGetBag
	(*BillCreatePayment)(nil),         // 11: proto.BillCreatePayment
	(*BillGetPayment)(nil),            // 12: proto.BillGetPayment
	(*BillUpdatePaymentStatus)(nil),   // 13: proto.BillUpdatePaymentStatus
	(*BillGetUserPayments)(nil),       // 14: proto.BillGetUserPayments
	(*ChatSendMessage)(nil),           // 15: proto.ChatSendMessage
	(*ChatGetMessages)(nil),           // 16: proto.ChatGetMessages
	(*ChatGetConversations)(nil),      // 17: proto.ChatGetConversations
	(*ChatUpdateMessageStatus)(nil),   // 18: proto.ChatUpdateMessageStatus
	(*Response)(nil),                  // 19: proto.Response
	(*AuthResponse)(nil),              // 20: proto.AuthResponse
	(*GameResponse)(nil),              // 21: proto.GameResponse
	(*BillResponse)(nil),              // 22: proto.BillResponse
	(*ChatResponse)(nil),              // 23: proto.ChatResponse
	(*CharacterList)(nil),             // 24: proto.CharacterList
	(*BagItemList)(nil),               // 25: proto.BagItemList
	(*PaymentList)(nil),               // 26: proto.PaymentList
	(*MessageList)(nil),               // 27: proto.MessageList
	(*ConversationList)(nil),          // 28: proto.ConversationList
	(*Character)(nil),                 // 29: proto.Character
	(*BattleResult)(nil),              // 30: proto.BattleResult
	(*BagItemData)(nil),               // 31: proto.BagItemData
	(*Payment)(nil),                   // 32: proto.Payment
	(*Conversation)(nil),              // 33: proto.Conversation
}
var file_common_proto_depIdxs = []int32{
	0,  // 0: proto.Message.type:type_name -> proto.MessageType
	2,  // 1: proto.Message.auth_register:type_name -> proto.AuthRegister
	3,  // 2: proto.Message.auth_login:type_name -> proto.AuthLogin
	4,  // 3: proto.Message.auth_validate:type_name -> proto.AuthValidate
	5,  // 4: proto.Message.game_create_character:type_name -> proto.GameCreateCharacter
	6,  // 5: proto.Message.game_get_characters:type_name -> proto.GameGetCharacters
	7,  // 6: proto.Message.game_get_character:type_name -> proto.GameGetCharacter
	8,  // 7: proto.Message.game_update_character_status:type_name -> proto.GameUpdateCharacterStatus
	9,  // 8: proto.Message.game_battle:type_name -> proto.GameBattle
	10, // 9: proto.Message.game_get_bag:type_name -> proto.GameGetBag
	11, // 10: proto.Message.bill_create_payment:type_name -> proto.BillCreatePayment
	12, // 11: proto.Message.bill_get_payment:type_name -> proto.BillGetPayment
	13, // 12: proto.Message.bill_update_payment_status:type_name -> proto.BillUpdatePaymentStatus
	14, // 13: proto.Message.bill_get_user_payments:type_name -> proto.BillGetUserPayments
	15, // 14: proto.Message.chat_send_message:type_name -> proto.ChatSendMessage
	16, // 15: proto.Message.chat_get_messages:type_name -> proto.ChatGetMessages
	17, // 16: proto.Message.chat_get_conversations:type_name -> proto.ChatGetConversations
	18, // 17: proto.Message.chat_update_message_status:type_name -> proto.ChatUpdateMessageStatus
	19, // 18: proto.Message.response:type_name -> proto.Response
	20, // 19: proto.Response.auth_response:type_name -> proto.AuthResponse
	21, // 20: proto.Response.game_response:type_name -> proto.GameResponse
	22, // 21: proto.Response.bill_response:type_name -> proto.BillResponse
	23, // 22: proto.Response.chat_response:type_name -> proto.ChatResponse
	29, // 23: proto.GameResponse.character:type_name -> proto.Character
	24, // 24: proto.GameResponse.characters:type_name -> proto.CharacterList
	30, // 25: proto.GameResponse.battle_result:type_name -> proto.BattleResult
	25, // 26: proto.GameResponse.bag_items:type_name -> proto.BagItemList
	32, // 27: proto.BillResponse.payment:type_name -> proto.Payment
	26, // 28: proto.BillResponse.payments:type_name -> proto.PaymentList
	1,  // 29: proto.ChatResponse.chat_message:type_name -> proto.Message
	27, // 30: proto.ChatResponse.chat_messages:type_name -> proto.MessageList
	28, // 31: proto.ChatResponse.conversations:type_name -> proto.ConversationList
	29, // 32: proto.CharacterList.items:type_name -> proto.Character
	31, // 33: proto.BagItemList.items:type_name -> proto.BagItemData
	32, // 34: proto.PaymentList.items:type_name -> proto.Payment
	1,  // 35: proto.MessageList.items:type_name -> proto.Message
	33, // 36: proto.ConversationList.items:type_name -> proto.Conversation
	37, // [37:37] is the sub-list for method output_type
	37, // [37:37] is the sub-list for method input_type
	37, // [37:37] is the sub-list for extension type_name
	37, // [37:37] is the sub-list for extension extendee
	0,  // [0:37] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_AuthRegister)(nil),
		(*Message_AuthLogin)(nil),
		(*Message_AuthValidate)(nil),
		(*Message_GameCreateCharacter)(nil),
		(*Message_GameGetCharacters)(nil),
		(*Message_GameGetCharacter)(nil),
		(*Message_GameUpdateCharacterStatus)(nil),
		(*Message_GameBattle)(nil),
		(*Message_GameGetBag)(nil),
		(*Message_BillCreatePayment)(nil),
		(*Message_BillGetPayment)(nil),
		(*Message_BillUpdatePaymentStatus)(nil),
		(*Message_BillGetUserPayments)(nil),
		(*Message_ChatSendMessage)(nil),
		(*Message_ChatGetMessages)(nil),
		(*Message_ChatGetConversations)(nil),
		(*Message_ChatUpdateMessageStatus)(nil),
		(*Message_Response)(nil),
	}
	file_common_proto_msgTypes[18].OneofWrappers = []any{
		(*Response_AuthResponse)(nil),
		(*Response_GameResponse)(nil),
		(*Response_BillResponse)(nil),
		(*Response_ChatResponse)(nil),
	}
	file_common_proto_msgTypes[20].OneofWrappers = []any{
		(*GameResponse_Character)(nil),
		(*GameResponse_Characters)(nil),
		(*GameResponse_BattleResult)(nil),
		(*GameResponse_BagItems)(nil),
	}
	file_common_proto_msgTypes[21].OneofWrappers = []any{
		(*BillResponse_Payment)(nil),
		(*BillResponse_Payments)(nil),
		(*BillResponse_Total)(nil),
	}
	file_common_proto_msgTypes[22].OneofWrappers = []any{
		(*ChatResponse_ChatMessage)(nil),
		(*ChatResponse_ChatMessages)(nil),
		(*ChatResponse_Conversations)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
