// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushMessageRequest 推送消息请求
type PushMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MessageType   string                 `protobuf:"bytes,2,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	MessageData   []byte                 `protobuf:"bytes,3,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageRequest) Reset() {
	*x = PushMessageRequest{}
	mi := &file_proto_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageRequest) ProtoMessage() {}

func (x *PushMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageRequest.ProtoReflect.Descriptor instead.
func (*PushMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PushMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *PushMessageRequest) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *PushMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PushMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// PushMessageResponse 推送消息响应
type PushMessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error            string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ConnectedClients int32                  `protobuf:"varint,3,opt,name=connected_clients,json=connectedClients,proto3" json:"connected_clients,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushMessageResponse) Reset() {
	*x = PushMessageResponse{}
	mi := &file_proto_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResponse) ProtoMessage() {}

func (x *PushMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResponse.ProtoReflect.Descriptor instead.
func (*PushMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *PushMessageResponse) GetConnectedClients() int32 {
	if x != nil {
		return x.ConnectedClients
	}
	return 0
}

// BroadcastMessageRequest 广播消息请求
type BroadcastMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageType   string                 `protobuf:"bytes,1,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	MessageData   []byte                 `protobuf:"bytes,2,opt,name=message_data,json=messageData,proto3" json:"message_data,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BroadcastMessageRequest) Reset() {
	*x = BroadcastMessageRequest{}
	mi := &file_proto_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessageRequest) ProtoMessage() {}

func (x *BroadcastMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessageRequest.ProtoReflect.Descriptor instead.
func (*BroadcastMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *BroadcastMessageRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BroadcastMessageRequest) GetMessageData() []byte {
	if x != nil {
		return x.MessageData
	}
	return nil
}

func (x *BroadcastMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BroadcastMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// BroadcastMessageResponse 广播消息响应
type BroadcastMessageResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	BroadcastCount int32                  `protobuf:"varint,3,opt,name=broadcast_count,json=broadcastCount,proto3" json:"broadcast_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastMessageResponse) Reset() {
	*x = BroadcastMessageResponse{}
	mi := &file_proto_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastMessageResponse) ProtoMessage() {}

func (x *BroadcastMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastMessageResponse.ProtoReflect.Descriptor instead.
func (*BroadcastMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *BroadcastMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BroadcastMessageResponse) GetBroadcastCount() int32 {
	if x != nil {
		return x.BroadcastCount
	}
	return 0
}

// GetConnectedUsersRequest 获取连接用户列表请求
type GetConnectedUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectedUsersRequest) Reset() {
	*x = GetConnectedUsersRequest{}
	mi := &file_proto_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectedUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectedUsersRequest) ProtoMessage() {}

func (x *GetConnectedUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectedUsersRequest.ProtoReflect.Descriptor instead.
func (*GetConnectedUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{4}
}

// GetConnectedUsersResponse 获取连接用户列表响应
type GetConnectedUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []uint32               `protobuf:"varint,1,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	TotalUsers    int32                  `protobuf:"varint,2,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectedUsersResponse) Reset() {
	*x = GetConnectedUsersResponse{}
	mi := &file_proto_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectedUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectedUsersResponse) ProtoMessage() {}

func (x *GetConnectedUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectedUsersResponse.ProtoReflect.Descriptor instead.
func (*GetConnectedUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *GetConnectedUsersResponse) GetUserIds() []uint32 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *GetConnectedUsersResponse) GetTotalUsers() int32 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetConnectedUsersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_gateway_proto protoreflect.FileDescriptor

const file_proto_gateway_proto_rawDesc = "" +
	"\n" +
	"\x13proto/gateway.proto\x12\agateway\"\xa3\x01\n" +
	"\x12PushMessageRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12!\n" +
	"\fmessage_type\x18\x02 \x01(\tR\vmessageType\x12!\n" +
	"\fmessage_data\x18\x03 \x01(\fR\vmessageData\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\"r\n" +
	"\x13PushMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12+\n" +
	"\x11connected_clients\x18\x03 \x01(\x05R\x10connectedClients\"\x8f\x01\n" +
	"\x17BroadcastMessageRequest\x12!\n" +
	"\fmessage_type\x18\x01 \x01(\tR\vmessageType\x12!\n" +
	"\fmessage_data\x18\x02 \x01(\fR\vmessageData\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\"s\n" +
	"\x18BroadcastMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12'\n" +
	"\x0fbroadcast_count\x18\x03 \x01(\x05R\x0ebroadcastCount\"\x1a\n" +
	"\x18GetConnectedUsersRequest\"m\n" +
	"\x19GetConnectedUsersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\rR\auserIds\x12\x1f\n" +
	"\vtotal_users\x18\x02 \x01(\x05R\n" +
	"totalUsers\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2\x95\x02\n" +
	"\x0eGatewayService\x12J\n" +
	"\vPushMessage\x12\x1b.gateway.PushMessageRequest\x1a\x1c.gateway.PushMessageResponse\"\x00\x12Y\n" +
	"\x10BroadcastMessage\x12 .gateway.BroadcastMessageRequest\x1a!.gateway.BroadcastMessageResponse\"\x00\x12\\\n" +
	"\x11GetConnectedUsers\x12!.gateway.GetConnectedUsersRequest\x1a\".gateway.GetConnectedUsersResponse\"\x00B&Z$github.com/aoyo/qp/pkg/proto/gatewayb\x06proto3"

var (
	file_proto_gateway_proto_rawDescOnce sync.Once
	file_proto_gateway_proto_rawDescData []byte
)

func file_proto_gateway_proto_rawDescGZIP() []byte {
	file_proto_gateway_proto_rawDescOnce.Do(func() {
		file_proto_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)))
	})
	return file_proto_gateway_proto_rawDescData
}

var file_proto_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_gateway_proto_goTypes = []any{
	(*PushMessageRequest)(nil),        // 0: gateway.PushMessageRequest
	(*PushMessageResponse)(nil),       // 1: gateway.PushMessageResponse
	(*BroadcastMessageRequest)(nil),   // 2: gateway.BroadcastMessageRequest
	(*BroadcastMessageResponse)(nil),  // 3: gateway.BroadcastMessageResponse
	(*GetConnectedUsersRequest)(nil),  // 4: gateway.GetConnectedUsersRequest
	(*GetConnectedUsersResponse)(nil), // 5: gateway.GetConnectedUsersResponse
}
var file_proto_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.PushMessage:input_type -> gateway.PushMessageRequest
	2, // 1: gateway.GatewayService.BroadcastMessage:input_type -> gateway.BroadcastMessageRequest
	4, // 2: gateway.GatewayService.GetConnectedUsers:input_type -> gateway.GetConnectedUsersRequest
	1, // 3: gateway.GatewayService.PushMessage:output_type -> gateway.PushMessageResponse
	3, // 4: gateway.GatewayService.BroadcastMessage:output_type -> gateway.BroadcastMessageResponse
	5, // 5: gateway.GatewayService.GetConnectedUsers:output_type -> gateway.GetConnectedUsersResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gateway_proto_init() }
func file_proto_gateway_proto_init() {
	if File_proto_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_gateway_proto_rawDesc), len(file_proto_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gateway_proto_goTypes,
		DependencyIndexes: file_proto_gateway_proto_depIdxs,
		MessageInfos:      file_proto_gateway_proto_msgTypes,
	}.Build()
	File_proto_gateway_proto = out.File
	file_proto_gateway_proto_goTypes = nil
	file_proto_gateway_proto_depIdxs = nil
}
