// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: gamelogic/equip.proto

package gamelogic

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 装备信息
type EquipData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipId       int64                  `protobuf:"varint,1,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"`            //唯一编号
	EquipCfgId    int32                  `protobuf:"varint,2,opt,name=equip_cfg_id,json=equipCfgId,proto3" json:"equip_cfg_id,omitempty"` //配表id
	ExtInfo       string                 `protobuf:"bytes,100,opt,name=ext_info,json=extInfo,proto3" json:"ext_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EquipData) Reset() {
	*x = EquipData{}
	mi := &file_gamelogic_equip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipData) ProtoMessage() {}

func (x *EquipData) ProtoReflect() protoreflect.Message {
	mi := &file_gamelogic_equip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipData.ProtoReflect.Descriptor instead.
func (*EquipData) Descriptor() ([]byte, []int) {
	return file_gamelogic_equip_proto_rawDescGZIP(), []int{0}
}

func (x *EquipData) GetEquipId() int64 {
	if x != nil {
		return x.EquipId
	}
	return 0
}

func (x *EquipData) GetEquipCfgId() int32 {
	if x != nil {
		return x.EquipCfgId
	}
	return 0
}

func (x *EquipData) GetExtInfo() string {
	if x != nil {
		return x.ExtInfo
	}
	return ""
}

// 获取装备请求
type GetEquipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipRequest) Reset() {
	*x = GetEquipRequest{}
	mi := &file_gamelogic_equip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipRequest) ProtoMessage() {}

func (x *GetEquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamelogic_equip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipRequest.ProtoReflect.Descriptor instead.
func (*GetEquipRequest) Descriptor() ([]byte, []int) {
	return file_gamelogic_equip_proto_rawDescGZIP(), []int{1}
}

// 获取装备响应
type GetEquipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ResultErr             `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Data          []*EquipData           `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEquipResponse) Reset() {
	*x = GetEquipResponse{}
	mi := &file_gamelogic_equip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEquipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEquipResponse) ProtoMessage() {}

func (x *GetEquipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamelogic_equip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEquipResponse.ProtoReflect.Descriptor instead.
func (*GetEquipResponse) Descriptor() ([]byte, []int) {
	return file_gamelogic_equip_proto_rawDescGZIP(), []int{2}
}

func (x *GetEquipResponse) GetErr() *ResultErr {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *GetEquipResponse) GetData() []*EquipData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpgradeEquipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EquipId       int64                  `protobuf:"varint,1,opt,name=equip_id,json=equipId,proto3" json:"equip_id,omitempty"` //唯一编号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeEquipRequest) Reset() {
	*x = UpgradeEquipRequest{}
	mi := &file_gamelogic_equip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeEquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEquipRequest) ProtoMessage() {}

func (x *UpgradeEquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gamelogic_equip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEquipRequest.ProtoReflect.Descriptor instead.
func (*UpgradeEquipRequest) Descriptor() ([]byte, []int) {
	return file_gamelogic_equip_proto_rawDescGZIP(), []int{3}
}

func (x *UpgradeEquipRequest) GetEquipId() int64 {
	if x != nil {
		return x.EquipId
	}
	return 0
}

// 装备升级响应
type UpgradeEquipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Err           *ResultErr             `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Data          *EquipData             `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpgradeEquipResponse) Reset() {
	*x = UpgradeEquipResponse{}
	mi := &file_gamelogic_equip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpgradeEquipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradeEquipResponse) ProtoMessage() {}

func (x *UpgradeEquipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gamelogic_equip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradeEquipResponse.ProtoReflect.Descriptor instead.
func (*UpgradeEquipResponse) Descriptor() ([]byte, []int) {
	return file_gamelogic_equip_proto_rawDescGZIP(), []int{4}
}

func (x *UpgradeEquipResponse) GetErr() *ResultErr {
	if x != nil {
		return x.Err
	}
	return nil
}

func (x *UpgradeEquipResponse) GetData() *EquipData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_gamelogic_equip_proto protoreflect.FileDescriptor

const file_gamelogic_equip_proto_rawDesc = "" +
	"\n" +
	"\x15gamelogic/equip.proto\x12\bprotocli\x1a\x14gamelogic/base.proto\"c\n" +
	"\tEquipData\x12\x19\n" +
	"\bequip_id\x18\x01 \x01(\x03R\aequipId\x12 \n" +
	"\fequip_cfg_id\x18\x02 \x01(\x05R\n" +
	"equipCfgId\x12\x19\n" +
	"\bext_info\x18d \x01(\tR\aextInfo\"\x11\n" +
	"\x0fGetEquipRequest\"b\n" +
	"\x10GetEquipResponse\x12%\n" +
	"\x03err\x18\x01 \x01(\v2\x13.protocli.ResultErrR\x03err\x12'\n" +
	"\x04data\x18\x02 \x03(\v2\x13.protocli.EquipDataR\x04data\"0\n" +
	"\x13UpgradeEquipRequest\x12\x19\n" +
	"\bequip_id\x18\x01 \x01(\x03R\aequipId\"f\n" +
	"\x14UpgradeEquipResponse\x12%\n" +
	"\x03err\x18\x01 \x01(\v2\x13.protocli.ResultErrR\x03err\x12'\n" +
	"\x04data\x18\x02 \x01(\v2\x13.protocli.EquipDataR\x04dataB\x1bZ\x19zgame/pb/golang/gamelogicb\x06proto3"

var (
	file_gamelogic_equip_proto_rawDescOnce sync.Once
	file_gamelogic_equip_proto_rawDescData []byte
)

func file_gamelogic_equip_proto_rawDescGZIP() []byte {
	file_gamelogic_equip_proto_rawDescOnce.Do(func() {
		file_gamelogic_equip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gamelogic_equip_proto_rawDesc), len(file_gamelogic_equip_proto_rawDesc)))
	})
	return file_gamelogic_equip_proto_rawDescData
}

var file_gamelogic_equip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gamelogic_equip_proto_goTypes = []any{
	(*EquipData)(nil),            // 0: protocli.EquipData
	(*GetEquipRequest)(nil),      // 1: protocli.GetEquipRequest
	(*GetEquipResponse)(nil),     // 2: protocli.GetEquipResponse
	(*UpgradeEquipRequest)(nil),  // 3: protocli.UpgradeEquipRequest
	(*UpgradeEquipResponse)(nil), // 4: protocli.UpgradeEquipResponse
	(*ResultErr)(nil),            // 5: protocli.ResultErr
}
var file_gamelogic_equip_proto_depIdxs = []int32{
	5, // 0: protocli.GetEquipResponse.err:type_name -> protocli.ResultErr
	0, // 1: protocli.GetEquipResponse.data:type_name -> protocli.EquipData
	5, // 2: protocli.UpgradeEquipResponse.err:type_name -> protocli.ResultErr
	0, // 3: protocli.UpgradeEquipResponse.data:type_name -> protocli.EquipData
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_gamelogic_equip_proto_init() }
func file_gamelogic_equip_proto_init() {
	if File_gamelogic_equip_proto != nil {
		return
	}
	file_gamelogic_base_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gamelogic_equip_proto_rawDesc), len(file_gamelogic_equip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gamelogic_equip_proto_goTypes,
		DependencyIndexes: file_gamelogic_equip_proto_depIdxs,
		MessageInfos:      file_gamelogic_equip_proto_msgTypes,
	}.Build()
	File_gamelogic_equip_proto = out.File
	file_gamelogic_equip_proto_goTypes = nil
	file_gamelogic_equip_proto_depIdxs = nil
}
