// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type MessageType int32

const (
	MessageType_MSG_TYPE_UNKNOWN MessageType = 0
	// 认证相关
	MessageType_MSG_TYPE_AUTH_REGISTER MessageType = 1
	MessageType_MSG_TYPE_AUTH_LOGIN    MessageType = 2
	MessageType_MSG_TYPE_AUTH_VALIDATE MessageType = 3
	// 游戏相关
	MessageType_MSG_TYPE_GAME_CREATE_CHARACTER        MessageType = 4
	MessageType_MSG_TYPE_GAME_GET_CHARACTERS          MessageType = 5
	MessageType_MSG_TYPE_GAME_GET_CHARACTER           MessageType = 6
	MessageType_MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS MessageType = 7
	MessageType_MSG_TYPE_GAME_BATTLE                  MessageType = 8
	// 代币相关
	MessageType_MSG_TYPE_BILL_GET_TOKEN_BALANCE MessageType = 9
	MessageType_MSG_TYPE_BILL_ADD_TOKEN         MessageType = 10
	MessageType_MSG_TYPE_BILL_REMOVE_TOKEN      MessageType = 11
	// 支付相关
	MessageType_MSG_TYPE_BILL_CREATE_PAYMENT MessageType = 12
	MessageType_MSG_TYPE_BILL_GET_PAYMENT    MessageType = 13
	// 通用响应
	MessageType_MSG_TYPE_RESPONSE MessageType = 100
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MSG_TYPE_UNKNOWN",
		1:   "MSG_TYPE_AUTH_REGISTER",
		2:   "MSG_TYPE_AUTH_LOGIN",
		3:   "MSG_TYPE_AUTH_VALIDATE",
		4:   "MSG_TYPE_GAME_CREATE_CHARACTER",
		5:   "MSG_TYPE_GAME_GET_CHARACTERS",
		6:   "MSG_TYPE_GAME_GET_CHARACTER",
		7:   "MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS",
		8:   "MSG_TYPE_GAME_BATTLE",
		9:   "MSG_TYPE_BILL_GET_TOKEN_BALANCE",
		10:  "MSG_TYPE_BILL_ADD_TOKEN",
		11:  "MSG_TYPE_BILL_REMOVE_TOKEN",
		12:  "MSG_TYPE_BILL_CREATE_PAYMENT",
		13:  "MSG_TYPE_BILL_GET_PAYMENT",
		100: "MSG_TYPE_RESPONSE",
	}
	MessageType_value = map[string]int32{
		"MSG_TYPE_UNKNOWN":                      0,
		"MSG_TYPE_AUTH_REGISTER":                1,
		"MSG_TYPE_AUTH_LOGIN":                   2,
		"MSG_TYPE_AUTH_VALIDATE":                3,
		"MSG_TYPE_GAME_CREATE_CHARACTER":        4,
		"MSG_TYPE_GAME_GET_CHARACTERS":          5,
		"MSG_TYPE_GAME_GET_CHARACTER":           6,
		"MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS": 7,
		"MSG_TYPE_GAME_BATTLE":                  8,
		"MSG_TYPE_BILL_GET_TOKEN_BALANCE":       9,
		"MSG_TYPE_BILL_ADD_TOKEN":               10,
		"MSG_TYPE_BILL_REMOVE_TOKEN":            11,
		"MSG_TYPE_BILL_CREATE_PAYMENT":          12,
		"MSG_TYPE_BILL_GET_PAYMENT":             13,
		"MSG_TYPE_RESPONSE":                     100,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_proto_game_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

// 基础消息结构
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=game.MessageType" json:"type,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Message_AuthRegister
	//	*Message_AuthLogin
	//	*Message_AuthValidate
	//	*Message_GameCreateCharacter
	//	*Message_GameGetCharacters
	//	*Message_GameGetCharacter
	//	*Message_GameUpdateCharacterStatus
	//	*Message_GameBattle
	//	*Message_BillGetTokenBalance
	//	*Message_BillAddToken
	//	*Message_BillRemoveToken
	//	*Message_BillCreatePayment
	//	*Message_BillGetPayment
	//	*Message_Response
	Data          isMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_TYPE_UNKNOWN
}

func (x *Message) GetData() isMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Message) GetAuthRegister() *AuthRegisterRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_AuthRegister); ok {
			return x.AuthRegister
		}
	}
	return nil
}

func (x *Message) GetAuthLogin() *AuthLoginRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_AuthLogin); ok {
			return x.AuthLogin
		}
	}
	return nil
}

func (x *Message) GetAuthValidate() *AuthValidateRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_AuthValidate); ok {
			return x.AuthValidate
		}
	}
	return nil
}

func (x *Message) GetGameCreateCharacter() *GameCreateCharacterRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_GameCreateCharacter); ok {
			return x.GameCreateCharacter
		}
	}
	return nil
}

func (x *Message) GetGameGetCharacters() *GameGetCharactersRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_GameGetCharacters); ok {
			return x.GameGetCharacters
		}
	}
	return nil
}

func (x *Message) GetGameGetCharacter() *GameGetCharacterRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_GameGetCharacter); ok {
			return x.GameGetCharacter
		}
	}
	return nil
}

func (x *Message) GetGameUpdateCharacterStatus() *GameUpdateCharacterStatusRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_GameUpdateCharacterStatus); ok {
			return x.GameUpdateCharacterStatus
		}
	}
	return nil
}

func (x *Message) GetGameBattle() *GameBattleRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_GameBattle); ok {
			return x.GameBattle
		}
	}
	return nil
}

func (x *Message) GetBillGetTokenBalance() *BillGetTokenBalanceRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_BillGetTokenBalance); ok {
			return x.BillGetTokenBalance
		}
	}
	return nil
}

func (x *Message) GetBillAddToken() *BillAddTokenRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_BillAddToken); ok {
			return x.BillAddToken
		}
	}
	return nil
}

func (x *Message) GetBillRemoveToken() *BillRemoveTokenRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_BillRemoveToken); ok {
			return x.BillRemoveToken
		}
	}
	return nil
}

func (x *Message) GetBillCreatePayment() *BillCreatePaymentRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_BillCreatePayment); ok {
			return x.BillCreatePayment
		}
	}
	return nil
}

func (x *Message) GetBillGetPayment() *BillGetPaymentRequest {
	if x != nil {
		if x, ok := x.Data.(*Message_BillGetPayment); ok {
			return x.BillGetPayment
		}
	}
	return nil
}

func (x *Message) GetResponse() *Response {
	if x != nil {
		if x, ok := x.Data.(*Message_Response); ok {
			return x.Response
		}
	}
	return nil
}

type isMessage_Data interface {
	isMessage_Data()
}

type Message_AuthRegister struct {
	AuthRegister *AuthRegisterRequest `protobuf:"bytes,2,opt,name=auth_register,json=authRegister,proto3,oneof"`
}

type Message_AuthLogin struct {
	AuthLogin *AuthLoginRequest `protobuf:"bytes,3,opt,name=auth_login,json=authLogin,proto3,oneof"`
}

type Message_AuthValidate struct {
	AuthValidate *AuthValidateRequest `protobuf:"bytes,4,opt,name=auth_validate,json=authValidate,proto3,oneof"`
}

type Message_GameCreateCharacter struct {
	GameCreateCharacter *GameCreateCharacterRequest `protobuf:"bytes,5,opt,name=game_create_character,json=gameCreateCharacter,proto3,oneof"`
}

type Message_GameGetCharacters struct {
	GameGetCharacters *GameGetCharactersRequest `protobuf:"bytes,6,opt,name=game_get_characters,json=gameGetCharacters,proto3,oneof"`
}

type Message_GameGetCharacter struct {
	GameGetCharacter *GameGetCharacterRequest `protobuf:"bytes,7,opt,name=game_get_character,json=gameGetCharacter,proto3,oneof"`
}

type Message_GameUpdateCharacterStatus struct {
	GameUpdateCharacterStatus *GameUpdateCharacterStatusRequest `protobuf:"bytes,8,opt,name=game_update_character_status,json=gameUpdateCharacterStatus,proto3,oneof"`
}

type Message_GameBattle struct {
	GameBattle *GameBattleRequest `protobuf:"bytes,9,opt,name=game_battle,json=gameBattle,proto3,oneof"`
}

type Message_BillGetTokenBalance struct {
	BillGetTokenBalance *BillGetTokenBalanceRequest `protobuf:"bytes,10,opt,name=bill_get_token_balance,json=billGetTokenBalance,proto3,oneof"`
}

type Message_BillAddToken struct {
	BillAddToken *BillAddTokenRequest `protobuf:"bytes,11,opt,name=bill_add_token,json=billAddToken,proto3,oneof"`
}

type Message_BillRemoveToken struct {
	BillRemoveToken *BillRemoveTokenRequest `protobuf:"bytes,12,opt,name=bill_remove_token,json=billRemoveToken,proto3,oneof"`
}

type Message_BillCreatePayment struct {
	BillCreatePayment *BillCreatePaymentRequest `protobuf:"bytes,13,opt,name=bill_create_payment,json=billCreatePayment,proto3,oneof"`
}

type Message_BillGetPayment struct {
	BillGetPayment *BillGetPaymentRequest `protobuf:"bytes,14,opt,name=bill_get_payment,json=billGetPayment,proto3,oneof"`
}

type Message_Response struct {
	Response *Response `protobuf:"bytes,100,opt,name=response,proto3,oneof"`
}

func (*Message_AuthRegister) isMessage_Data() {}

func (*Message_AuthLogin) isMessage_Data() {}

func (*Message_AuthValidate) isMessage_Data() {}

func (*Message_GameCreateCharacter) isMessage_Data() {}

func (*Message_GameGetCharacters) isMessage_Data() {}

func (*Message_GameGetCharacter) isMessage_Data() {}

func (*Message_GameUpdateCharacterStatus) isMessage_Data() {}

func (*Message_GameBattle) isMessage_Data() {}

func (*Message_BillGetTokenBalance) isMessage_Data() {}

func (*Message_BillAddToken) isMessage_Data() {}

func (*Message_BillRemoveToken) isMessage_Data() {}

func (*Message_BillCreatePayment) isMessage_Data() {}

func (*Message_BillGetPayment) isMessage_Data() {}

func (*Message_Response) isMessage_Data() {}

// 认证相关消息
type AuthRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRegisterRequest) Reset() {
	*x = AuthRegisterRequest{}
	mi := &file_proto_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRegisterRequest) ProtoMessage() {}

func (x *AuthRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRegisterRequest.ProtoReflect.Descriptor instead.
func (*AuthRegisterRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{1}
}

func (x *AuthRegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthRegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type AuthLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthLoginRequest) Reset() {
	*x = AuthLoginRequest{}
	mi := &file_proto_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthLoginRequest) ProtoMessage() {}

func (x *AuthLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthLoginRequest.ProtoReflect.Descriptor instead.
func (*AuthLoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{2}
}

func (x *AuthLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthValidateRequest) Reset() {
	*x = AuthValidateRequest{}
	mi := &file_proto_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthValidateRequest) ProtoMessage() {}

func (x *AuthValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthValidateRequest.ProtoReflect.Descriptor instead.
func (*AuthValidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{3}
}

func (x *AuthValidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// 游戏相关消息
type GameCreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCreateCharacterRequest) Reset() {
	*x = GameCreateCharacterRequest{}
	mi := &file_proto_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCreateCharacterRequest) ProtoMessage() {}

func (x *GameCreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*GameCreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{4}
}

func (x *GameCreateCharacterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameCreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GameGetCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameGetCharactersRequest) Reset() {
	*x = GameGetCharactersRequest{}
	mi := &file_proto_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameGetCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetCharactersRequest) ProtoMessage() {}

func (x *GameGetCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetCharactersRequest.ProtoReflect.Descriptor instead.
func (*GameGetCharactersRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{5}
}

func (x *GameGetCharactersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GameGetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameGetCharacterRequest) Reset() {
	*x = GameGetCharacterRequest{}
	mi := &file_proto_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameGetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameGetCharacterRequest) ProtoMessage() {}

func (x *GameGetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameGetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GameGetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{6}
}

func (x *GameGetCharacterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GameUpdateCharacterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameUpdateCharacterStatusRequest) Reset() {
	*x = GameUpdateCharacterStatusRequest{}
	mi := &file_proto_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameUpdateCharacterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameUpdateCharacterStatusRequest) ProtoMessage() {}

func (x *GameUpdateCharacterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameUpdateCharacterStatusRequest.ProtoReflect.Descriptor instead.
func (*GameUpdateCharacterStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{7}
}

func (x *GameUpdateCharacterStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameUpdateCharacterStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type GameBattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	EnemyLevel    int32                  `protobuf:"varint,2,opt,name=enemy_level,json=enemyLevel,proto3" json:"enemy_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBattleRequest) Reset() {
	*x = GameBattleRequest{}
	mi := &file_proto_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBattleRequest) ProtoMessage() {}

func (x *GameBattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBattleRequest.ProtoReflect.Descriptor instead.
func (*GameBattleRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{8}
}

func (x *GameBattleRequest) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GameBattleRequest) GetEnemyLevel() int32 {
	if x != nil {
		return x.EnemyLevel
	}
	return 0
}

// 代币相关消息
type BillGetTokenBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillGetTokenBalanceRequest) Reset() {
	*x = BillGetTokenBalanceRequest{}
	mi := &file_proto_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillGetTokenBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillGetTokenBalanceRequest) ProtoMessage() {}

func (x *BillGetTokenBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillGetTokenBalanceRequest.ProtoReflect.Descriptor instead.
func (*BillGetTokenBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{9}
}

func (x *BillGetTokenBalanceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillGetTokenBalanceRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type BillAddTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillAddTokenRequest) Reset() {
	*x = BillAddTokenRequest{}
	mi := &file_proto_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillAddTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillAddTokenRequest) ProtoMessage() {}

func (x *BillAddTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillAddTokenRequest.ProtoReflect.Descriptor instead.
func (*BillAddTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{10}
}

func (x *BillAddTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillAddTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *BillAddTokenRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BillRemoveTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillRemoveTokenRequest) Reset() {
	*x = BillRemoveTokenRequest{}
	mi := &file_proto_game_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillRemoveTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillRemoveTokenRequest) ProtoMessage() {}

func (x *BillRemoveTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillRemoveTokenRequest.ProtoReflect.Descriptor instead.
func (*BillRemoveTokenRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{11}
}

func (x *BillRemoveTokenRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillRemoveTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *BillRemoveTokenRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// 支付相关消息
type BillCreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	TokenType     string                 `protobuf:"bytes,4,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	TokenAmount   int64                  `protobuf:"varint,5,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,6,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillCreatePaymentRequest) Reset() {
	*x = BillCreatePaymentRequest{}
	mi := &file_proto_game_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillCreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillCreatePaymentRequest) ProtoMessage() {}

func (x *BillCreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillCreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*BillCreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{12}
}

func (x *BillCreatePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillCreatePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillCreatePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BillCreatePaymentRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *BillCreatePaymentRequest) GetTokenAmount() int64 {
	if x != nil {
		return x.TokenAmount
	}
	return 0
}

func (x *BillCreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

type BillGetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillGetPaymentRequest) Reset() {
	*x = BillGetPaymentRequest{}
	mi := &file_proto_game_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillGetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillGetPaymentRequest) ProtoMessage() {}

func (x *BillGetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillGetPaymentRequest.ProtoReflect.Descriptor instead.
func (*BillGetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{13}
}

func (x *BillGetPaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

// 响应消息
type Response struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*Response_AuthResponse
	//	*Response_GameCharacterResponse
	//	*Response_GameCharactersResponse
	//	*Response_GameBattleResponse
	//	*Response_BillTokenBalanceResponse
	//	*Response_BillPaymentResponse
	Data          isResponse_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_game_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{14}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() isResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetAuthResponse() *AuthResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_AuthResponse); ok {
			return x.AuthResponse
		}
	}
	return nil
}

func (x *Response) GetGameCharacterResponse() *GameCharacterResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_GameCharacterResponse); ok {
			return x.GameCharacterResponse
		}
	}
	return nil
}

func (x *Response) GetGameCharactersResponse() *GameCharactersResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_GameCharactersResponse); ok {
			return x.GameCharactersResponse
		}
	}
	return nil
}

func (x *Response) GetGameBattleResponse() *GameBattleResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_GameBattleResponse); ok {
			return x.GameBattleResponse
		}
	}
	return nil
}

func (x *Response) GetBillTokenBalanceResponse() *BillTokenBalanceResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_BillTokenBalanceResponse); ok {
			return x.BillTokenBalanceResponse
		}
	}
	return nil
}

func (x *Response) GetBillPaymentResponse() *BillPaymentResponse {
	if x != nil {
		if x, ok := x.Data.(*Response_BillPaymentResponse); ok {
			return x.BillPaymentResponse
		}
	}
	return nil
}

type isResponse_Data interface {
	isResponse_Data()
}

type Response_AuthResponse struct {
	AuthResponse *AuthResponse `protobuf:"bytes,3,opt,name=auth_response,json=authResponse,proto3,oneof"`
}

type Response_GameCharacterResponse struct {
	GameCharacterResponse *GameCharacterResponse `protobuf:"bytes,4,opt,name=game_character_response,json=gameCharacterResponse,proto3,oneof"`
}

type Response_GameCharactersResponse struct {
	GameCharactersResponse *GameCharactersResponse `protobuf:"bytes,5,opt,name=game_characters_response,json=gameCharactersResponse,proto3,oneof"`
}

type Response_GameBattleResponse struct {
	GameBattleResponse *GameBattleResponse `protobuf:"bytes,6,opt,name=game_battle_response,json=gameBattleResponse,proto3,oneof"`
}

type Response_BillTokenBalanceResponse struct {
	BillTokenBalanceResponse *BillTokenBalanceResponse `protobuf:"bytes,7,opt,name=bill_token_balance_response,json=billTokenBalanceResponse,proto3,oneof"`
}

type Response_BillPaymentResponse struct {
	BillPaymentResponse *BillPaymentResponse `protobuf:"bytes,8,opt,name=bill_payment_response,json=billPaymentResponse,proto3,oneof"`
}

func (*Response_AuthResponse) isResponse_Data() {}

func (*Response_GameCharacterResponse) isResponse_Data() {}

func (*Response_GameCharactersResponse) isResponse_Data() {}

func (*Response_GameBattleResponse) isResponse_Data() {}

func (*Response_BillTokenBalanceResponse) isResponse_Data() {}

func (*Response_BillPaymentResponse) isResponse_Data() {}

// 认证响应
type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_game_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{15}
}

func (x *AuthResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *AuthResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// 游戏角色响应
type GameCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int32                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Hp            int32                  `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            int32                  `protobuf:"varint,7,opt,name=mp,proto3" json:"mp,omitempty"`
	Attack        int32                  `protobuf:"varint,8,opt,name=attack,proto3" json:"attack,omitempty"`
	Defense       int32                  `protobuf:"varint,9,opt,name=defense,proto3" json:"defense,omitempty"`
	Status        int32                  `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCharacterResponse) Reset() {
	*x = GameCharacterResponse{}
	mi := &file_proto_game_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCharacterResponse) ProtoMessage() {}

func (x *GameCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCharacterResponse.ProtoReflect.Descriptor instead.
func (*GameCharacterResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{16}
}

func (x *GameCharacterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GameCharacterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GameCharacterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameCharacterResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *GameCharacterResponse) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *GameCharacterResponse) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *GameCharacterResponse) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *GameCharacterResponse) GetAttack() int32 {
	if x != nil {
		return x.Attack
	}
	return 0
}

func (x *GameCharacterResponse) GetDefense() int32 {
	if x != nil {
		return x.Defense
	}
	return 0
}

func (x *GameCharacterResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 游戏角色列表响应
type GameCharactersResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Characters    []*GameCharacterResponse `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameCharactersResponse) Reset() {
	*x = GameCharactersResponse{}
	mi := &file_proto_game_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameCharactersResponse) ProtoMessage() {}

func (x *GameCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameCharactersResponse.ProtoReflect.Descriptor instead.
func (*GameCharactersResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{17}
}

func (x *GameCharactersResponse) GetCharacters() []*GameCharacterResponse {
	if x != nil {
		return x.Characters
	}
	return nil
}

// 游戏战斗响应
type GameBattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   string                 `protobuf:"bytes,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	EnemyLevel    int32                  `protobuf:"varint,2,opt,name=enemy_level,json=enemyLevel,proto3" json:"enemy_level,omitempty"`
	Victory       bool                   `protobuf:"varint,3,opt,name=victory,proto3" json:"victory,omitempty"`
	ExpGained     int32                  `protobuf:"varint,4,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`
	GoldGained    int32                  `protobuf:"varint,5,opt,name=gold_gained,json=goldGained,proto3" json:"gold_gained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameBattleResponse) Reset() {
	*x = GameBattleResponse{}
	mi := &file_proto_game_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameBattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameBattleResponse) ProtoMessage() {}

func (x *GameBattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameBattleResponse.ProtoReflect.Descriptor instead.
func (*GameBattleResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{18}
}

func (x *GameBattleResponse) GetCharacterId() string {
	if x != nil {
		return x.CharacterId
	}
	return ""
}

func (x *GameBattleResponse) GetEnemyLevel() int32 {
	if x != nil {
		return x.EnemyLevel
	}
	return 0
}

func (x *GameBattleResponse) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *GameBattleResponse) GetExpGained() int32 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

func (x *GameBattleResponse) GetGoldGained() int32 {
	if x != nil {
		return x.GoldGained
	}
	return 0
}

// 代币余额响应
type BillTokenBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TokenType     string                 `protobuf:"bytes,2,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	Balance       int64                  `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
	Locked        int64                  `protobuf:"varint,4,opt,name=locked,proto3" json:"locked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillTokenBalanceResponse) Reset() {
	*x = BillTokenBalanceResponse{}
	mi := &file_proto_game_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillTokenBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillTokenBalanceResponse) ProtoMessage() {}

func (x *BillTokenBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillTokenBalanceResponse.ProtoReflect.Descriptor instead.
func (*BillTokenBalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{19}
}

func (x *BillTokenBalanceResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillTokenBalanceResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *BillTokenBalanceResponse) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *BillTokenBalanceResponse) GetLocked() int64 {
	if x != nil {
		return x.Locked
	}
	return 0
}

// 支付响应
type BillPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	TokenType     string                 `protobuf:"bytes,5,opt,name=token_type,json=tokenType,proto3" json:"token_type,omitempty"`
	TokenAmount   int64                  `protobuf:"varint,6,opt,name=token_amount,json=tokenAmount,proto3" json:"token_amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,9,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PaymentUrl    string                 `protobuf:"bytes,10,opt,name=payment_url,json=paymentUrl,proto3" json:"payment_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillPaymentResponse) Reset() {
	*x = BillPaymentResponse{}
	mi := &file_proto_game_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillPaymentResponse) ProtoMessage() {}

func (x *BillPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillPaymentResponse.ProtoReflect.Descriptor instead.
func (*BillPaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_game_proto_rawDescGZIP(), []int{20}
}

func (x *BillPaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *BillPaymentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BillPaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillPaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *BillPaymentResponse) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

func (x *BillPaymentResponse) GetTokenAmount() int64 {
	if x != nil {
		return x.TokenAmount
	}
	return 0
}

func (x *BillPaymentResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *BillPaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BillPaymentResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BillPaymentResponse) GetPaymentUrl() string {
	if x != nil {
		return x.PaymentUrl
	}
	return ""
}

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\"\xc6\b\n" +
	"\aMessage\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.game.MessageTypeR\x04type\x12@\n" +
	"\rauth_register\x18\x02 \x01(\v2\x19.game.AuthRegisterRequestH\x00R\fauthRegister\x127\n" +
	"\n" +
	"auth_login\x18\x03 \x01(\v2\x16.game.AuthLoginRequestH\x00R\tauthLogin\x12@\n" +
	"\rauth_validate\x18\x04 \x01(\v2\x19.game.AuthValidateRequestH\x00R\fauthValidate\x12V\n" +
	"\x15game_create_character\x18\x05 \x01(\v2 .game.GameCreateCharacterRequestH\x00R\x13gameCreateCharacter\x12P\n" +
	"\x13game_get_characters\x18\x06 \x01(\v2\x1e.game.GameGetCharactersRequestH\x00R\x11gameGetCharacters\x12M\n" +
	"\x12game_get_character\x18\a \x01(\v2\x1d.game.GameGetCharacterRequestH\x00R\x10gameGetCharacter\x12i\n" +
	"\x1cgame_update_character_status\x18\b \x01(\v2&.game.GameUpdateCharacterStatusRequestH\x00R\x19gameUpdateCharacterStatus\x12:\n" +
	"\vgame_battle\x18\t \x01(\v2\x17.game.GameBattleRequestH\x00R\n" +
	"gameBattle\x12W\n" +
	"\x16bill_get_token_balance\x18\n" +
	" \x01(\v2 .game.BillGetTokenBalanceRequestH\x00R\x13billGetTokenBalance\x12A\n" +
	"\x0ebill_add_token\x18\v \x01(\v2\x19.game.BillAddTokenRequestH\x00R\fbillAddToken\x12J\n" +
	"\x11bill_remove_token\x18\f \x01(\v2\x1c.game.BillRemoveTokenRequestH\x00R\x0fbillRemoveToken\x12P\n" +
	"\x13bill_create_payment\x18\r \x01(\v2\x1e.game.BillCreatePaymentRequestH\x00R\x11billCreatePayment\x12G\n" +
	"\x10bill_get_payment\x18\x0e \x01(\v2\x1b.game.BillGetPaymentRequestH\x00R\x0ebillGetPayment\x12,\n" +
	"\bresponse\x18d \x01(\v2\x0e.game.ResponseH\x00R\bresponseB\x06\n" +
	"\x04data\"\x7f\n" +
	"\x13AuthRegisterRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"J\n" +
	"\x10AuthLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x13AuthValidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x1aGameCreateCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"3\n" +
	"\x18GameGetCharactersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\")\n" +
	"\x17GameGetCharacterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	" GameUpdateCharacterStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"W\n" +
	"\x11GameBattleRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x1f\n" +
	"\venemy_level\x18\x02 \x01(\x05R\n" +
	"enemyLevel\"T\n" +
	"\x1aBillGetTokenBalanceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\"e\n" +
	"\x13BillAddTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"h\n" +
	"\x16BillRemoveTokenRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\"\xd0\x01\n" +
	"\x18BillCreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"token_type\x18\x04 \x01(\tR\ttokenType\x12!\n" +
	"\ftoken_amount\x18\x05 \x01(\x03R\vtokenAmount\x12%\n" +
	"\x0epayment_method\x18\x06 \x01(\tR\rpaymentMethod\"2\n" +
	"\x15BillGetPaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\xac\x04\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\rauth_response\x18\x03 \x01(\v2\x12.game.AuthResponseH\x00R\fauthResponse\x12U\n" +
	"\x17game_character_response\x18\x04 \x01(\v2\x1b.game.GameCharacterResponseH\x00R\x15gameCharacterResponse\x12X\n" +
	"\x18game_characters_response\x18\x05 \x01(\v2\x1c.game.GameCharactersResponseH\x00R\x16gameCharactersResponse\x12L\n" +
	"\x14game_battle_response\x18\x06 \x01(\v2\x18.game.GameBattleResponseH\x00R\x12gameBattleResponse\x12_\n" +
	"\x1bbill_token_balance_response\x18\a \x01(\v2\x1e.game.BillTokenBalanceResponseH\x00R\x18billTokenBalanceResponse\x12O\n" +
	"\x15bill_payment_response\x18\b \x01(\v2\x19.game.BillPaymentResponseH\x00R\x13billPaymentResponseB\x06\n" +
	"\x04data\"u\n" +
	"\fAuthResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x04 \x01(\tR\bnickname\"\xe6\x01\n" +
	"\x15GameCharacterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x05R\x03exp\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\x05R\x02hp\x12\x0e\n" +
	"\x02mp\x18\a \x01(\x05R\x02mp\x12\x16\n" +
	"\x06attack\x18\b \x01(\x05R\x06attack\x12\x18\n" +
	"\adefense\x18\t \x01(\x05R\adefense\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\x05R\x06status\"U\n" +
	"\x16GameCharactersResponse\x12;\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x1b.game.GameCharacterResponseR\n" +
	"characters\"\xb2\x01\n" +
	"\x12GameBattleResponse\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\tR\vcharacterId\x12\x1f\n" +
	"\venemy_level\x18\x02 \x01(\x05R\n" +
	"enemyLevel\x12\x18\n" +
	"\avictory\x18\x03 \x01(\bR\avictory\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\x04 \x01(\x05R\texpGained\x12\x1f\n" +
	"\vgold_gained\x18\x05 \x01(\x05R\n" +
	"goldGained\"\x84\x01\n" +
	"\x18BillTokenBalanceResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenType\x12\x18\n" +
	"\abalance\x18\x03 \x01(\x03R\abalance\x12\x16\n" +
	"\x06locked\x18\x04 \x01(\x03R\x06locked\"\xc6\x02\n" +
	"\x13BillPaymentResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"token_type\x18\x05 \x01(\tR\ttokenType\x12!\n" +
	"\ftoken_amount\x18\x06 \x01(\x03R\vtokenAmount\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\t \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vpayment_url\x18\n" +
	" \x01(\tR\n" +
	"paymentUrl*\xda\x03\n" +
	"\vMessageType\x12\x14\n" +
	"\x10MSG_TYPE_UNKNOWN\x10\x00\x12\x1a\n" +
	"\x16MSG_TYPE_AUTH_REGISTER\x10\x01\x12\x17\n" +
	"\x13MSG_TYPE_AUTH_LOGIN\x10\x02\x12\x1a\n" +
	"\x16MSG_TYPE_AUTH_VALIDATE\x10\x03\x12\"\n" +
	"\x1eMSG_TYPE_GAME_CREATE_CHARACTER\x10\x04\x12 \n" +
	"\x1cMSG_TYPE_GAME_GET_CHARACTERS\x10\x05\x12\x1f\n" +
	"\x1bMSG_TYPE_GAME_GET_CHARACTER\x10\x06\x12)\n" +
	"%MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS\x10\a\x12\x18\n" +
	"\x14MSG_TYPE_GAME_BATTLE\x10\b\x12#\n" +
	"\x1fMSG_TYPE_BILL_GET_TOKEN_BALANCE\x10\t\x12\x1b\n" +
	"\x17MSG_TYPE_BILL_ADD_TOKEN\x10\n" +
	"\x12\x1e\n" +
	"\x1aMSG_TYPE_BILL_REMOVE_TOKEN\x10\v\x12 \n" +
	"\x1cMSG_TYPE_BILL_CREATE_PAYMENT\x10\f\x12\x1d\n" +
	"\x19MSG_TYPE_BILL_GET_PAYMENT\x10\r\x12\x15\n" +
	"\x11MSG_TYPE_RESPONSE\x10dB\x1aZ\x18github.com/aoyo/qp/protob\x06proto3"

var (
	file_proto_game_proto_rawDescOnce sync.Once
	file_proto_game_proto_rawDescData []byte
)

func file_proto_game_proto_rawDescGZIP() []byte {
	file_proto_game_proto_rawDescOnce.Do(func() {
		file_proto_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)))
	})
	return file_proto_game_proto_rawDescData
}

var file_proto_game_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_game_proto_goTypes = []any{
	(MessageType)(0),                         // 0: game.MessageType
	(*Message)(nil),                          // 1: game.Message
	(*AuthRegisterRequest)(nil),              // 2: game.AuthRegisterRequest
	(*AuthLoginRequest)(nil),                 // 3: game.AuthLoginRequest
	(*AuthValidateRequest)(nil),              // 4: game.AuthValidateRequest
	(*GameCreateCharacterRequest)(nil),       // 5: game.GameCreateCharacterRequest
	(*GameGetCharactersRequest)(nil),         // 6: game.GameGetCharactersRequest
	(*GameGetCharacterRequest)(nil),          // 7: game.GameGetCharacterRequest
	(*GameUpdateCharacterStatusRequest)(nil), // 8: game.GameUpdateCharacterStatusRequest
	(*GameBattleRequest)(nil),                // 9: game.GameBattleRequest
	(*BillGetTokenBalanceRequest)(nil),       // 10: game.BillGetTokenBalanceRequest
	(*BillAddTokenRequest)(nil),              // 11: game.BillAddTokenRequest
	(*BillRemoveTokenRequest)(nil),           // 12: game.BillRemoveTokenRequest
	(*BillCreatePaymentRequest)(nil),         // 13: game.BillCreatePaymentRequest
	(*BillGetPaymentRequest)(nil),            // 14: game.BillGetPaymentRequest
	(*Response)(nil),                         // 15: game.Response
	(*AuthResponse)(nil),                     // 16: game.AuthResponse
	(*GameCharacterResponse)(nil),            // 17: game.GameCharacterResponse
	(*GameCharactersResponse)(nil),           // 18: game.GameCharactersResponse
	(*GameBattleResponse)(nil),               // 19: game.GameBattleResponse
	(*BillTokenBalanceResponse)(nil),         // 20: game.BillTokenBalanceResponse
	(*BillPaymentResponse)(nil),              // 21: game.BillPaymentResponse
}
var file_proto_game_proto_depIdxs = []int32{
	0,  // 0: game.Message.type:type_name -> game.MessageType
	2,  // 1: game.Message.auth_register:type_name -> game.AuthRegisterRequest
	3,  // 2: game.Message.auth_login:type_name -> game.AuthLoginRequest
	4,  // 3: game.Message.auth_validate:type_name -> game.AuthValidateRequest
	5,  // 4: game.Message.game_create_character:type_name -> game.GameCreateCharacterRequest
	6,  // 5: game.Message.game_get_characters:type_name -> game.GameGetCharactersRequest
	7,  // 6: game.Message.game_get_character:type_name -> game.GameGetCharacterRequest
	8,  // 7: game.Message.game_update_character_status:type_name -> game.GameUpdateCharacterStatusRequest
	9,  // 8: game.Message.game_battle:type_name -> game.GameBattleRequest
	10, // 9: game.Message.bill_get_token_balance:type_name -> game.BillGetTokenBalanceRequest
	11, // 10: game.Message.bill_add_token:type_name -> game.BillAddTokenRequest
	12, // 11: game.Message.bill_remove_token:type_name -> game.BillRemoveTokenRequest
	13, // 12: game.Message.bill_create_payment:type_name -> game.BillCreatePaymentRequest
	14, // 13: game.Message.bill_get_payment:type_name -> game.BillGetPaymentRequest
	15, // 14: game.Message.response:type_name -> game.Response
	16, // 15: game.Response.auth_response:type_name -> game.AuthResponse
	17, // 16: game.Response.game_character_response:type_name -> game.GameCharacterResponse
	18, // 17: game.Response.game_characters_response:type_name -> game.GameCharactersResponse
	19, // 18: game.Response.game_battle_response:type_name -> game.GameBattleResponse
	20, // 19: game.Response.bill_token_balance_response:type_name -> game.BillTokenBalanceResponse
	21, // 20: game.Response.bill_payment_response:type_name -> game.BillPaymentResponse
	17, // 21: game.GameCharactersResponse.characters:type_name -> game.GameCharacterResponse
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_game_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_AuthRegister)(nil),
		(*Message_AuthLogin)(nil),
		(*Message_AuthValidate)(nil),
		(*Message_GameCreateCharacter)(nil),
		(*Message_GameGetCharacters)(nil),
		(*Message_GameGetCharacter)(nil),
		(*Message_GameUpdateCharacterStatus)(nil),
		(*Message_GameBattle)(nil),
		(*Message_BillGetTokenBalance)(nil),
		(*Message_BillAddToken)(nil),
		(*Message_BillRemoveToken)(nil),
		(*Message_BillCreatePayment)(nil),
		(*Message_BillGetPayment)(nil),
		(*Message_Response)(nil),
	}
	file_proto_game_proto_msgTypes[14].OneofWrappers = []any{
		(*Response_AuthResponse)(nil),
		(*Response_GameCharacterResponse)(nil),
		(*Response_GameCharactersResponse)(nil),
		(*Response_GameBattleResponse)(nil),
		(*Response_BillTokenBalanceResponse)(nil),
		(*Response_BillPaymentResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
		EnumInfos:         file_proto_game_proto_enumTypes,
		MessageInfos:      file_proto_game_proto_msgTypes,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
