// CocosJS code for bag
// Generated by proto generator
// Based on JSON serialization/deserialization

if (typeof window === 'undefined') {
	window = {};
}

if (!window.proto) {
	window.proto = {};
}

// bag namespace
window.proto.bag = {
	// Serialize message to JSON
	serialize: function(message) {
		return JSON.stringify(message);
	},
	
	// Deserialize JSON to message
	deserialize: function(json) {
		return JSON.parse(json);
	},
	
	// Message types
	MessageType: {
		
	},
	
	// Message wrapper
	Message: function(type, data) {
		this.type = type;
		this.data = data;
	},
	
	// BagItemData message
	BagItemData: function() {

	},
	// BagRequest message
	BagRequest: function() {

	},
	// BagResponse message
	BagResponse: function(BagItemData) {
		this.BagItemData = BagItemData;
	},
};

// Expose to CocosJS
try {
	if (cc && cc.Class) {
		cc.proto = window.proto;
	}
} catch (e) {
	// CocosJS not found, continue with window.proto
}
