// CocosJS code for game
// Generated by proto generator
// Based on JSON serialization/deserialization

if (typeof window === 'undefined') {
	window = {};
}

if (!window.proto) {
	window.proto = {};
}

// game namespace
window.proto.game = {
	// Serialize message to JSON
	serialize: function(message) {
		return JSON.stringify(message);
	},
	
	// Deserialize JSON to message
	deserialize: function(json) {
		return JSON.parse(json);
	},
	
	// Message types
	MessageType: {
		MSG_TYPE_UNKNOWN: 0,
		MSG_TYPE_AUTH_REGISTER: 1,
		MSG_TYPE_AUTH_LOGIN: 2,
		MSG_TYPE_AUTH_VALIDATE: 3,
		MSG_TYPE_GAME_CREATE_CHARACTER: 4,
		MSG_TYPE_GAME_GET_CHARACTERS: 5,
		MSG_TYPE_GAME_GET_CHARACTER: 6,
		MSG_TYPE_GAME_UPDATE_CHARACTER_STATUS: 7,
		MSG_TYPE_GAME_BATTLE: 8,
		MSG_TYPE_BILL_GET_TOKEN_BALANCE: 9,
		MSG_TYPE_BILL_ADD_TOKEN: 10,
		MSG_TYPE_BILL_REMOVE_TOKEN: 11,
		MSG_TYPE_BILL_CREATE_PAYMENT: 12,
		MSG_TYPE_BILL_GET_PAYMENT: 13,
		MSG_TYPE_RESPONSE: 100
	},
	
	// Message wrapper
	Message: function(type, data) {
		this.type = type;
		this.data = data;
	},
	
	// Message message
	Message: function(type) {
		this.type = type;
	},
	// AuthRegisterRequest message
	AuthRegisterRequest: function(username, password, email, nickname) {
		this.username = username;
		this.password = password;
		this.email = email;
		this.nickname = nickname;
	},
	// AuthLoginRequest message
	AuthLoginRequest: function(username, password) {
		this.username = username;
		this.password = password;
	},
	// AuthValidateRequest message
	AuthValidateRequest: function(token) {
		this.token = token;
	},
	// GameCreateCharacterRequest message
	GameCreateCharacterRequest: function(user_id, name) {
		this.user_id = user_id;
		this.name = name;
	},
	// GameGetCharactersRequest message
	GameGetCharactersRequest: function(user_id) {
		this.user_id = user_id;
	},
	// GameGetCharacterRequest message
	GameGetCharacterRequest: function(id) {
		this.id = id;
	},
	// GameUpdateCharacterStatusRequest message
	GameUpdateCharacterStatusRequest: function(id, status) {
		this.id = id;
		this.status = status;
	},
	// GameBattleRequest message
	GameBattleRequest: function(character_id, enemy_level) {
		this.character_id = character_id;
		this.enemy_level = enemy_level;
	},
	// BillGetTokenBalanceRequest message
	BillGetTokenBalanceRequest: function(user_id, token_type) {
		this.user_id = user_id;
		this.token_type = token_type;
	},
	// BillAddTokenRequest message
	BillAddTokenRequest: function(user_id, token_type, amount) {
		this.user_id = user_id;
		this.token_type = token_type;
		this.amount = amount;
	},
	// BillRemoveTokenRequest message
	BillRemoveTokenRequest: function(user_id, token_type, amount) {
		this.user_id = user_id;
		this.token_type = token_type;
		this.amount = amount;
	},
	// BillCreatePaymentRequest message
	BillCreatePaymentRequest: function(user_id, amount, currency, token_type, token_amount, payment_method) {
		this.user_id = user_id;
		this.amount = amount;
		this.currency = currency;
		this.token_type = token_type;
		this.token_amount = token_amount;
		this.payment_method = payment_method;
	},
	// BillGetPaymentRequest message
	BillGetPaymentRequest: function(order_id) {
		this.order_id = order_id;
	},
	// Response message
	Response: function(code, message) {
		this.code = code;
		this.message = message;
	},
	// AuthResponse message
	AuthResponse: function(token, user_id, username, nickname) {
		this.token = token;
		this.user_id = user_id;
		this.username = username;
		this.nickname = nickname;
	},
	// GameCharacterResponse message
	GameCharacterResponse: function(id, user_id, name, level, exp, hp, mp, attack, defense, status) {
		this.id = id;
		this.user_id = user_id;
		this.name = name;
		this.level = level;
		this.exp = exp;
		this.hp = hp;
		this.mp = mp;
		this.attack = attack;
		this.defense = defense;
		this.status = status;
	},
	// GameCharactersResponse message
	GameCharactersResponse: function(characters) {
		this.characters = characters;
	},
	// GameBattleResponse message
	GameBattleResponse: function(character_id, enemy_level, victory, exp_gained, gold_gained) {
		this.character_id = character_id;
		this.enemy_level = enemy_level;
		this.victory = victory;
		this.exp_gained = exp_gained;
		this.gold_gained = gold_gained;
	},
	// BillTokenBalanceResponse message
	BillTokenBalanceResponse: function(user_id, token_type, balance, locked) {
		this.user_id = user_id;
		this.token_type = token_type;
		this.balance = balance;
		this.locked = locked;
	},
	// BillPaymentResponse message
	BillPaymentResponse: function(order_id, user_id, amount, currency, token_type, token_amount, payment_method, status, transaction_id, payment_url) {
		this.order_id = order_id;
		this.user_id = user_id;
		this.amount = amount;
		this.currency = currency;
		this.token_type = token_type;
		this.token_amount = token_amount;
		this.payment_method = payment_method;
		this.status = status;
		this.transaction_id = transaction_id;
		this.payment_url = payment_url;
	},
};

// Expose to CocosJS
try {
	if (cc && cc.Class) {
		cc.proto = window.proto;
	}
} catch (e) {
	// CocosJS not found, continue with window.proto
}
