# Server Configuration
server:
  gateway:
    port: 9080
  gamelogic:
    port: 9000
  ssoauth:
    port: 9090
  bill:
    port: 9100
  chat:
    port: 9110

# MongoDB Configuration
database:
  host: 192.168.175.128
  port: 27017
  user: admin
  password: 1234
  dbname: qp_game

# WebSocket Configuration
websocket:
  path: /ws
  read_buffer_size: 1024
  write_buffer_size: 1024

# JWT Configuration
jwt:
  secret: your_jwt_secret_key
  expire_hours: 24
