// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: grpc/gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 服务器信息
type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`          // 服务器ID
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`    // 服务器名称
	StartMsgId    int32                  `protobuf:"varint,3,opt,name=start_msg_id,json=startMsgId,proto3" json:"start_msg_id,omitempty"` // 起始消息ID
	EndMsgId      int32                  `protobuf:"varint,4,opt,name=end_msg_id,json=endMsgId,proto3" json:"end_msg_id,omitempty"`       // 结束消息ID
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`                            // 服务器地址
	Port          int32                  `protobuf:"varint,6,opt,name=port,proto3" json:"port,omitempty"`                                 // 服务器端口
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_grpc_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *ServerInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *ServerInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *ServerInfo) GetStartMsgId() int32 {
	if x != nil {
		return x.StartMsgId
	}
	return 0
}

func (x *ServerInfo) GetEndMsgId() int32 {
	if x != nil {
		return x.EndMsgId
	}
	return 0
}

func (x *ServerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// 注册服务器请求
type RegisterServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerInfo    *ServerInfo            `protobuf:"bytes,1,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"` // 服务器信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServerRequest) Reset() {
	*x = RegisterServerRequest{}
	mi := &file_grpc_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerRequest) ProtoMessage() {}

func (x *RegisterServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterServerRequest) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterServerRequest) GetServerInfo() *ServerInfo {
	if x != nil {
		return x.ServerInfo
	}
	return nil
}

// 注册服务器响应
type RegisterServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // 是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`  // 消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterServerResponse) Reset() {
	*x = RegisterServerResponse{}
	mi := &file_grpc_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterServerResponse) ProtoMessage() {}

func (x *RegisterServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterServerResponse.ProtoReflect.Descriptor instead.
func (*RegisterServerResponse) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterServerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterServerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 消息转发请求
type ForwardMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      int32                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`               // 消息ID
	Session        string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`                                     // 会话ID
	ClientIp       string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`                   // 客户端IP地址
	MessageContent []byte                 `protobuf:"bytes,4,opt,name=message_content,json=messageContent,proto3" json:"message_content,omitempty"` // 消息内容
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForwardMessageRequest) Reset() {
	*x = ForwardMessageRequest{}
	mi := &file_grpc_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessageRequest) ProtoMessage() {}

func (x *ForwardMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessageRequest.ProtoReflect.Descriptor instead.
func (*ForwardMessageRequest) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ForwardMessageRequest) GetMessageId() int32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *ForwardMessageRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *ForwardMessageRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ForwardMessageRequest) GetMessageContent() []byte {
	if x != nil {
		return x.MessageContent
	}
	return nil
}

// 消息转发响应
type ForwardMessageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                       // 是否成功
	Message         string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                        // 消息
	ResponseContent []byte                 `protobuf:"bytes,3,opt,name=response_content,json=responseContent,proto3" json:"response_content,omitempty"` // 响应内容
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ForwardMessageResponse) Reset() {
	*x = ForwardMessageResponse{}
	mi := &file_grpc_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardMessageResponse) ProtoMessage() {}

func (x *ForwardMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardMessageResponse.ProtoReflect.Descriptor instead.
func (*ForwardMessageResponse) Descriptor() ([]byte, []int) {
	return file_grpc_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardMessageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForwardMessageResponse) GetResponseContent() []byte {
	if x != nil {
		return x.ResponseContent
	}
	return nil
}

var File_grpc_gateway_proto protoreflect.FileDescriptor

const file_grpc_gateway_proto_rawDesc = "" +
	"\n" +
	"\x12grpc/gateway.proto\x12\agateway\"\xb8\x01\n" +
	"\n" +
	"ServerInfo\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12 \n" +
	"\fstart_msg_id\x18\x03 \x01(\x05R\n" +
	"startMsgId\x12\x1c\n" +
	"\n" +
	"end_msg_id\x18\x04 \x01(\x05R\bendMsgId\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x06 \x01(\x05R\x04port\"M\n" +
	"\x15RegisterServerRequest\x124\n" +
	"\vserver_info\x18\x01 \x01(\v2\x13.gateway.ServerInfoR\n" +
	"serverInfo\"L\n" +
	"\x16RegisterServerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x96\x01\n" +
	"\x15ForwardMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x05R\tmessageId\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12'\n" +
	"\x0fmessage_content\x18\x04 \x01(\fR\x0emessageContent\"w\n" +
	"\x16ForwardMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10response_content\x18\x03 \x01(\fR\x0fresponseContent2\xb6\x01\n" +
	"\x0eGatewayService\x12Q\n" +
	"\x0eRegisterServer\x12\x1e.gateway.RegisterServerRequest\x1a\x1f.gateway.RegisterServerResponse\x12Q\n" +
	"\x0eForwardMessage\x12\x1e.gateway.ForwardMessageRequest\x1a\x1f.gateway.ForwardMessageResponseB\vZ\t./gatewayb\x06proto3"

var (
	file_grpc_gateway_proto_rawDescOnce sync.Once
	file_grpc_gateway_proto_rawDescData []byte
)

func file_grpc_gateway_proto_rawDescGZIP() []byte {
	file_grpc_gateway_proto_rawDescOnce.Do(func() {
		file_grpc_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_gateway_proto_rawDesc), len(file_grpc_gateway_proto_rawDesc)))
	})
	return file_grpc_gateway_proto_rawDescData
}

var file_grpc_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_grpc_gateway_proto_goTypes = []any{
	(*ServerInfo)(nil),             // 0: gateway.ServerInfo
	(*RegisterServerRequest)(nil),  // 1: gateway.RegisterServerRequest
	(*RegisterServerResponse)(nil), // 2: gateway.RegisterServerResponse
	(*ForwardMessageRequest)(nil),  // 3: gateway.ForwardMessageRequest
	(*ForwardMessageResponse)(nil), // 4: gateway.ForwardMessageResponse
}
var file_grpc_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.RegisterServerRequest.server_info:type_name -> gateway.ServerInfo
	1, // 1: gateway.GatewayService.RegisterServer:input_type -> gateway.RegisterServerRequest
	3, // 2: gateway.GatewayService.ForwardMessage:input_type -> gateway.ForwardMessageRequest
	2, // 3: gateway.GatewayService.RegisterServer:output_type -> gateway.RegisterServerResponse
	4, // 4: gateway.GatewayService.ForwardMessage:output_type -> gateway.ForwardMessageResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_grpc_gateway_proto_init() }
func file_grpc_gateway_proto_init() {
	if File_grpc_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_gateway_proto_rawDesc), len(file_grpc_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_gateway_proto_goTypes,
		DependencyIndexes: file_grpc_gateway_proto_depIdxs,
		MessageInfos:      file_grpc_gateway_proto_msgTypes,
	}.Build()
	File_grpc_gateway_proto = out.File
	file_grpc_gateway_proto_goTypes = nil
	file_grpc_gateway_proto_depIdxs = nil
}
