// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: bill.proto

package bill

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreatePaymentRequest 创建支付请求
type CreatePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,2,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        string                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,4,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentRequest) Reset() {
	*x = CreatePaymentRequest{}
	mi := &file_bill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentRequest) ProtoMessage() {}

func (x *CreatePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentRequest) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePaymentRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreatePaymentRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreatePaymentRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *CreatePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

// CreatePaymentResponse 创建支付响应
type CreatePaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentResponse) Reset() {
	*x = CreatePaymentResponse{}
	mi := &file_bill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentResponse) ProtoMessage() {}

func (x *CreatePaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentResponse) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *CreatePaymentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetPaymentRequest 获取支付信息请求
type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint32                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_bill_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetPaymentId() uint32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

// GetPaymentResponse 获取支付信息响应
type GetPaymentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Payment               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentResponse) Reset() {
	*x = GetPaymentResponse{}
	mi := &file_bill_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentResponse) ProtoMessage() {}

func (x *GetPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentResponse.ProtoReflect.Descriptor instead.
func (*GetPaymentResponse) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{3}
}

func (x *GetPaymentResponse) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *GetPaymentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpdatePaymentStatusRequest 更新支付状态请求
type UpdatePaymentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     uint32                 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusRequest) Reset() {
	*x = UpdatePaymentStatusRequest{}
	mi := &file_bill_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusRequest) ProtoMessage() {}

func (x *UpdatePaymentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusRequest) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePaymentStatusRequest) GetPaymentId() uint32 {
	if x != nil {
		return x.PaymentId
	}
	return 0
}

func (x *UpdatePaymentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// UpdatePaymentStatusResponse 更新支付状态响应
type UpdatePaymentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePaymentStatusResponse) Reset() {
	*x = UpdatePaymentStatusResponse{}
	mi := &file_bill_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePaymentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePaymentStatusResponse) ProtoMessage() {}

func (x *UpdatePaymentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePaymentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdatePaymentStatusResponse) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePaymentStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdatePaymentStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetUserPaymentsRequest 获取用户支付记录请求
type GetUserPaymentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPaymentsRequest) Reset() {
	*x = GetUserPaymentsRequest{}
	mi := &file_bill_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentsRequest) ProtoMessage() {}

func (x *GetUserPaymentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentsRequest.ProtoReflect.Descriptor instead.
func (*GetUserPaymentsRequest) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserPaymentsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserPaymentsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserPaymentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// GetUserPaymentsResponse 获取用户支付记录响应
type GetUserPaymentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payments      []*Payment             `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPaymentsResponse) Reset() {
	*x = GetUserPaymentsResponse{}
	mi := &file_bill_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPaymentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPaymentsResponse) ProtoMessage() {}

func (x *GetUserPaymentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPaymentsResponse.ProtoReflect.Descriptor instead.
func (*GetUserPaymentsResponse) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserPaymentsResponse) GetPayments() []*Payment {
	if x != nil {
		return x.Payments
	}
	return nil
}

func (x *GetUserPaymentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetUserPaymentsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Payment 支付信息
type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PaymentMethod string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_bill_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_bill_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_bill_proto_rawDescGZIP(), []int{8}
}

func (x *Payment) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Payment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Payment) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Payment) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_bill_proto protoreflect.FileDescriptor

const file_bill_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"bill.proto\x12\x04bill\"\x8d\x01\n" +
	"\x14CreatePaymentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x02 \x01(\tR\tproductId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\tR\x06amount\x12%\n" +
	"\x0epayment_method\x18\x04 \x01(\tR\rpaymentMethod\"V\n" +
	"\x15CreatePaymentResponse\x12'\n" +
	"\apayment\x18\x01 \x01(\v2\r.bill.PaymentR\apayment\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\rR\tpaymentId\"S\n" +
	"\x12GetPaymentResponse\x12'\n" +
	"\apayment\x18\x01 \x01(\v2\r.bill.PaymentR\apayment\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\x1aUpdatePaymentStatusRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\rR\tpaymentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"M\n" +
	"\x1bUpdatePaymentStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"b\n" +
	"\x16GetUserPaymentsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"p\n" +
	"\x17GetUserPaymentsResponse\x12)\n" +
	"\bpayments\x18\x01 \x03(\v2\r.bill.PaymentR\bpayments\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8d\x02\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt2\xcc\x02\n" +
	"\vBillService\x12J\n" +
	"\rCreatePayment\x12\x1a.bill.CreatePaymentRequest\x1a\x1b.bill.CreatePaymentResponse\"\x00\x12A\n" +
	"\n" +
	"GetPayment\x12\x17.bill.GetPaymentRequest\x1a\x18.bill.GetPaymentResponse\"\x00\x12\\\n" +
	"\x13UpdatePaymentStatus\x12 .bill.UpdatePaymentStatusRequest\x1a!.bill.UpdatePaymentStatusResponse\"\x00\x12P\n" +
	"\x0fGetUserPayments\x12\x1c.bill.GetUserPaymentsRequest\x1a\x1d.bill.GetUserPaymentsResponse\"\x00B#Z!github.com/aoyo/qp/pkg/proto/billb\x06proto3"

var (
	file_bill_proto_rawDescOnce sync.Once
	file_bill_proto_rawDescData []byte
)

func file_bill_proto_rawDescGZIP() []byte {
	file_bill_proto_rawDescOnce.Do(func() {
		file_bill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bill_proto_rawDesc), len(file_bill_proto_rawDesc)))
	})
	return file_bill_proto_rawDescData
}

var file_bill_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_bill_proto_goTypes = []any{
	(*CreatePaymentRequest)(nil),        // 0: bill.CreatePaymentRequest
	(*CreatePaymentResponse)(nil),       // 1: bill.CreatePaymentResponse
	(*GetPaymentRequest)(nil),           // 2: bill.GetPaymentRequest
	(*GetPaymentResponse)(nil),          // 3: bill.GetPaymentResponse
	(*UpdatePaymentStatusRequest)(nil),  // 4: bill.UpdatePaymentStatusRequest
	(*UpdatePaymentStatusResponse)(nil), // 5: bill.UpdatePaymentStatusResponse
	(*GetUserPaymentsRequest)(nil),      // 6: bill.GetUserPaymentsRequest
	(*GetUserPaymentsResponse)(nil),     // 7: bill.GetUserPaymentsResponse
	(*Payment)(nil),                     // 8: bill.Payment
}
var file_bill_proto_depIdxs = []int32{
	8, // 0: bill.CreatePaymentResponse.payment:type_name -> bill.Payment
	8, // 1: bill.GetPaymentResponse.payment:type_name -> bill.Payment
	8, // 2: bill.GetUserPaymentsResponse.payments:type_name -> bill.Payment
	0, // 3: bill.BillService.CreatePayment:input_type -> bill.CreatePaymentRequest
	2, // 4: bill.BillService.GetPayment:input_type -> bill.GetPaymentRequest
	4, // 5: bill.BillService.UpdatePaymentStatus:input_type -> bill.UpdatePaymentStatusRequest
	6, // 6: bill.BillService.GetUserPayments:input_type -> bill.GetUserPaymentsRequest
	1, // 7: bill.BillService.CreatePayment:output_type -> bill.CreatePaymentResponse
	3, // 8: bill.BillService.GetPayment:output_type -> bill.GetPaymentResponse
	5, // 9: bill.BillService.UpdatePaymentStatus:output_type -> bill.UpdatePaymentStatusResponse
	7, // 10: bill.BillService.GetUserPayments:output_type -> bill.GetUserPaymentsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_bill_proto_init() }
func file_bill_proto_init() {
	if File_bill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bill_proto_rawDesc), len(file_bill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bill_proto_goTypes,
		DependencyIndexes: file_bill_proto_depIdxs,
		MessageInfos:      file_bill_proto_msgTypes,
	}.Build()
	File_bill_proto = out.File
	file_bill_proto_goTypes = nil
	file_bill_proto_depIdxs = nil
}
