// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: bag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BagItemData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int64                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemCfgId     int32                  `protobuf:"varint,2,opt,name=item_cfg_id,json=itemCfgId,proto3" json:"item_cfg_id,omitempty"`
	Num           int64                  `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagItemData) Reset() {
	*x = BagItemData{}
	mi := &file_bag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagItemData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagItemData) ProtoMessage() {}

func (x *BagItemData) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagItemData.ProtoReflect.Descriptor instead.
func (*BagItemData) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{0}
}

func (x *BagItemData) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BagItemData) GetItemCfgId() int32 {
	if x != nil {
		return x.ItemCfgId
	}
	return 0
}

func (x *BagItemData) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type BagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagRequest) Reset() {
	*x = BagRequest{}
	mi := &file_bag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagRequest) ProtoMessage() {}

func (x *BagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagRequest.ProtoReflect.Descriptor instead.
func (*BagRequest) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{1}
}

type BagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BagItemData         `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BagResponse) Reset() {
	*x = BagResponse{}
	mi := &file_bag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BagResponse) ProtoMessage() {}

func (x *BagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BagResponse.ProtoReflect.Descriptor instead.
func (*BagResponse) Descriptor() ([]byte, []int) {
	return file_bag_proto_rawDescGZIP(), []int{2}
}

func (x *BagResponse) GetItems() []*BagItemData {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_bag_proto protoreflect.FileDescriptor

const file_bag_proto_rawDesc = "" +
	"\n" +
	"\tbag.proto\x12\x04game\"X\n" +
	"\vBagItemData\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x03R\x06itemId\x12\x1e\n" +
	"\vitem_cfg_id\x18\x02 \x01(\x05R\titemCfgId\x12\x10\n" +
	"\x03num\x18\x03 \x01(\x03R\x03num\"\f\n" +
	"\n" +
	"BagRequest\"6\n" +
	"\vBagResponse\x12'\n" +
	"\x05items\x18\x01 \x03(\v2\x11.game.BagItemDataR\x05itemsB\x1aZ\x18github.com/aoyo/qp/protob\x06proto3"

var (
	file_bag_proto_rawDescOnce sync.Once
	file_bag_proto_rawDescData []byte
)

func file_bag_proto_rawDescGZIP() []byte {
	file_bag_proto_rawDescOnce.Do(func() {
		file_bag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bag_proto_rawDesc), len(file_bag_proto_rawDesc)))
	})
	return file_bag_proto_rawDescData
}

var file_bag_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bag_proto_goTypes = []any{
	(*BagItemData)(nil), // 0: game.BagItemData
	(*BagRequest)(nil),  // 1: game.BagRequest
	(*BagResponse)(nil), // 2: game.BagResponse
}
var file_bag_proto_depIdxs = []int32{
	0, // 0: game.BagResponse.items:type_name -> game.BagItemData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_bag_proto_init() }
func file_bag_proto_init() {
	if File_bag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bag_proto_rawDesc), len(file_bag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bag_proto_goTypes,
		DependencyIndexes: file_bag_proto_depIdxs,
		MessageInfos:      file_bag_proto_msgTypes,
	}.Build()
	File_bag_proto = out.File
	file_bag_proto_goTypes = nil
	file_bag_proto_depIdxs = nil
}
