// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: game.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateCharacterRequest 创建角色请求
type CreateCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterRequest) Reset() {
	*x = CreateCharacterRequest{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterRequest) ProtoMessage() {}

func (x *CreateCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterRequest.ProtoReflect.Descriptor instead.
func (*CreateCharacterRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCharacterRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateCharacterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// CreateCharacterResponse 创建角色响应
type CreateCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCharacterResponse) Reset() {
	*x = CreateCharacterResponse{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCharacterResponse) ProtoMessage() {}

func (x *CreateCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCharacterResponse.ProtoReflect.Descriptor instead.
func (*CreateCharacterResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *CreateCharacterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetCharactersRequest 获取角色列表请求
type GetCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharactersRequest) Reset() {
	*x = GetCharactersRequest{}
	mi := &file_game_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharactersRequest) ProtoMessage() {}

func (x *GetCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharactersRequest.ProtoReflect.Descriptor instead.
func (*GetCharactersRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *GetCharactersRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// GetCharactersResponse 获取角色列表响应
type GetCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Characters    []*Character           `protobuf:"bytes,1,rep,name=characters,proto3" json:"characters,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharactersResponse) Reset() {
	*x = GetCharactersResponse{}
	mi := &file_game_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharactersResponse) ProtoMessage() {}

func (x *GetCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharactersResponse.ProtoReflect.Descriptor instead.
func (*GetCharactersResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *GetCharactersResponse) GetCharacters() []*Character {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *GetCharactersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// GetCharacterRequest 获取角色详情请求
type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_game_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *GetCharacterRequest) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

// GetCharacterResponse 获取角色详情响应
type GetCharacterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Character     *Character             `protobuf:"bytes,1,opt,name=character,proto3" json:"character,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterResponse) Reset() {
	*x = GetCharacterResponse{}
	mi := &file_game_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterResponse) ProtoMessage() {}

func (x *GetCharacterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterResponse.ProtoReflect.Descriptor instead.
func (*GetCharacterResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *GetCharacterResponse) GetCharacter() *Character {
	if x != nil {
		return x.Character
	}
	return nil
}

func (x *GetCharacterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// UpdateCharacterStatusRequest 更新角色状态请求
type UpdateCharacterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterStatusRequest) Reset() {
	*x = UpdateCharacterStatusRequest{}
	mi := &file_game_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterStatusRequest) ProtoMessage() {}

func (x *UpdateCharacterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCharacterStatusRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCharacterStatusRequest) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *UpdateCharacterStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// UpdateCharacterStatusResponse 更新角色状态响应
type UpdateCharacterStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCharacterStatusResponse) Reset() {
	*x = UpdateCharacterStatusResponse{}
	mi := &file_game_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCharacterStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCharacterStatusResponse) ProtoMessage() {}

func (x *UpdateCharacterStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCharacterStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCharacterStatusResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCharacterStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateCharacterStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BattleRequest 战斗请求
type BattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterId   uint32                 `protobuf:"varint,1,opt,name=character_id,json=characterId,proto3" json:"character_id,omitempty"`
	EnemyLevel    int32                  `protobuf:"varint,2,opt,name=enemy_level,json=enemyLevel,proto3" json:"enemy_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRequest) Reset() {
	*x = BattleRequest{}
	mi := &file_game_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRequest) ProtoMessage() {}

func (x *BattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRequest.ProtoReflect.Descriptor instead.
func (*BattleRequest) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{8}
}

func (x *BattleRequest) GetCharacterId() uint32 {
	if x != nil {
		return x.CharacterId
	}
	return 0
}

func (x *BattleRequest) GetEnemyLevel() int32 {
	if x != nil {
		return x.EnemyLevel
	}
	return 0
}

// BattleResponse 战斗响应
type BattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Victory       bool                   `protobuf:"varint,1,opt,name=victory,proto3" json:"victory,omitempty"`
	ExpGained     int32                  `protobuf:"varint,2,opt,name=exp_gained,json=expGained,proto3" json:"exp_gained,omitempty"`
	GoldGained    int32                  `protobuf:"varint,3,opt,name=gold_gained,json=goldGained,proto3" json:"gold_gained,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResponse) Reset() {
	*x = BattleResponse{}
	mi := &file_game_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResponse) ProtoMessage() {}

func (x *BattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResponse.ProtoReflect.Descriptor instead.
func (*BattleResponse) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{9}
}

func (x *BattleResponse) GetVictory() bool {
	if x != nil {
		return x.Victory
	}
	return false
}

func (x *BattleResponse) GetExpGained() int32 {
	if x != nil {
		return x.ExpGained
	}
	return 0
}

func (x *BattleResponse) GetGoldGained() int32 {
	if x != nil {
		return x.GoldGained
	}
	return 0
}

func (x *BattleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BattleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Character 角色信息
type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Exp           int32                  `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	Hp            int32                  `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Mp            int32                  `protobuf:"varint,7,opt,name=mp,proto3" json:"mp,omitempty"`
	Strength      int32                  `protobuf:"varint,8,opt,name=strength,proto3" json:"strength,omitempty"`
	Agility       int32                  `protobuf:"varint,9,opt,name=agility,proto3" json:"agility,omitempty"`
	Intelligence  int32                  `protobuf:"varint,10,opt,name=intelligence,proto3" json:"intelligence,omitempty"`
	Gold          int32                  `protobuf:"varint,11,opt,name=gold,proto3" json:"gold,omitempty"`
	Status        int32                  `protobuf:"varint,12,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_game_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{10}
}

func (x *Character) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Character) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Character) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Character) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Character) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

func (x *Character) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *Character) GetMp() int32 {
	if x != nil {
		return x.Mp
	}
	return 0
}

func (x *Character) GetStrength() int32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *Character) GetAgility() int32 {
	if x != nil {
		return x.Agility
	}
	return 0
}

func (x *Character) GetIntelligence() int32 {
	if x != nil {
		return x.Intelligence
	}
	return 0
}

func (x *Character) GetGold() int32 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *Character) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\x04game\"E\n" +
	"\x16CreateCharacterRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"^\n" +
	"\x17CreateCharacterResponse\x12-\n" +
	"\tcharacter\x18\x01 \x01(\v2\x0f.game.CharacterR\tcharacter\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"/\n" +
	"\x14GetCharactersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\"^\n" +
	"\x15GetCharactersResponse\x12/\n" +
	"\n" +
	"characters\x18\x01 \x03(\v2\x0f.game.CharacterR\n" +
	"characters\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x13GetCharacterRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\"[\n" +
	"\x14GetCharacterResponse\x12-\n" +
	"\tcharacter\x18\x01 \x01(\v2\x0f.game.CharacterR\tcharacter\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Y\n" +
	"\x1cUpdateCharacterStatusRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\"O\n" +
	"\x1dUpdateCharacterStatusResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"S\n" +
	"\rBattleRequest\x12!\n" +
	"\fcharacter_id\x18\x01 \x01(\rR\vcharacterId\x12\x1f\n" +
	"\venemy_level\x18\x02 \x01(\x05R\n" +
	"enemyLevel\"\x9a\x01\n" +
	"\x0eBattleResponse\x12\x18\n" +
	"\avictory\x18\x01 \x01(\bR\avictory\x12\x1d\n" +
	"\n" +
	"exp_gained\x18\x02 \x01(\x05R\texpGained\x12\x1f\n" +
	"\vgold_gained\x18\x03 \x01(\x05R\n" +
	"goldGained\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x96\x02\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x10\n" +
	"\x03exp\x18\x05 \x01(\x05R\x03exp\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\x05R\x02hp\x12\x0e\n" +
	"\x02mp\x18\a \x01(\x05R\x02mp\x12\x1a\n" +
	"\bstrength\x18\b \x01(\x05R\bstrength\x12\x18\n" +
	"\aagility\x18\t \x01(\x05R\aagility\x12\"\n" +
	"\fintelligence\x18\n" +
	" \x01(\x05R\fintelligence\x12\x12\n" +
	"\x04gold\x18\v \x01(\x05R\x04gold\x12\x16\n" +
	"\x06status\x18\f \x01(\x05R\x06status2\x8f\x03\n" +
	"\vGameService\x12P\n" +
	"\x0fCreateCharacter\x12\x1c.game.CreateCharacterRequest\x1a\x1d.game.CreateCharacterResponse\"\x00\x12J\n" +
	"\rGetCharacters\x12\x1a.game.GetCharactersRequest\x1a\x1b.game.GetCharactersResponse\"\x00\x12G\n" +
	"\fGetCharacter\x12\x19.game.GetCharacterRequest\x1a\x1a.game.GetCharacterResponse\"\x00\x12b\n" +
	"\x15UpdateCharacterStatus\x12\".game.UpdateCharacterStatusRequest\x1a#.game.UpdateCharacterStatusResponse\"\x00\x125\n" +
	"\x06Battle\x12\x13.game.BattleRequest\x1a\x14.game.BattleResponse\"\x00B#Z!github.com/aoyo/qp/pkg/proto/gameb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_game_proto_goTypes = []any{
	(*CreateCharacterRequest)(nil),        // 0: game.CreateCharacterRequest
	(*CreateCharacterResponse)(nil),       // 1: game.CreateCharacterResponse
	(*GetCharactersRequest)(nil),          // 2: game.GetCharactersRequest
	(*GetCharactersResponse)(nil),         // 3: game.GetCharactersResponse
	(*GetCharacterRequest)(nil),           // 4: game.GetCharacterRequest
	(*GetCharacterResponse)(nil),          // 5: game.GetCharacterResponse
	(*UpdateCharacterStatusRequest)(nil),  // 6: game.UpdateCharacterStatusRequest
	(*UpdateCharacterStatusResponse)(nil), // 7: game.UpdateCharacterStatusResponse
	(*BattleRequest)(nil),                 // 8: game.BattleRequest
	(*BattleResponse)(nil),                // 9: game.BattleResponse
	(*Character)(nil),                     // 10: game.Character
}
var file_game_proto_depIdxs = []int32{
	10, // 0: game.CreateCharacterResponse.character:type_name -> game.Character
	10, // 1: game.GetCharactersResponse.characters:type_name -> game.Character
	10, // 2: game.GetCharacterResponse.character:type_name -> game.Character
	0,  // 3: game.GameService.CreateCharacter:input_type -> game.CreateCharacterRequest
	2,  // 4: game.GameService.GetCharacters:input_type -> game.GetCharactersRequest
	4,  // 5: game.GameService.GetCharacter:input_type -> game.GetCharacterRequest
	6,  // 6: game.GameService.UpdateCharacterStatus:input_type -> game.UpdateCharacterStatusRequest
	8,  // 7: game.GameService.Battle:input_type -> game.BattleRequest
	1,  // 8: game.GameService.CreateCharacter:output_type -> game.CreateCharacterResponse
	3,  // 9: game.GameService.GetCharacters:output_type -> game.GetCharactersResponse
	5,  // 10: game.GameService.GetCharacter:output_type -> game.GetCharacterResponse
	7,  // 11: game.GameService.UpdateCharacterStatus:output_type -> game.UpdateCharacterStatusResponse
	9,  // 12: game.GameService.Battle:output_type -> game.BattleResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
