// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: test_gateway.proto

package gateway

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterProtocolRangeRequest 注册协议编号段请求
type RegisterProtocolRangeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServiceName    string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`          // 服务名称
	ServiceAddress string                 `protobuf:"bytes,2,opt,name=service_address,json=serviceAddress,proto3" json:"service_address,omitempty"` // 服务地址
	StartProtocol  int32                  `protobuf:"varint,3,opt,name=start_protocol,json=startProtocol,proto3" json:"start_protocol,omitempty"`   // 起始协议编号
	EndProtocol    int32                  `protobuf:"varint,4,opt,name=end_protocol,json=endProtocol,proto3" json:"end_protocol,omitempty"`         // 结束协议编号
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterProtocolRangeRequest) Reset() {
	*x = RegisterProtocolRangeRequest{}
	mi := &file_test_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProtocolRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProtocolRangeRequest) ProtoMessage() {}

func (x *RegisterProtocolRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProtocolRangeRequest.ProtoReflect.Descriptor instead.
func (*RegisterProtocolRangeRequest) Descriptor() ([]byte, []int) {
	return file_test_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterProtocolRangeRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *RegisterProtocolRangeRequest) GetServiceAddress() string {
	if x != nil {
		return x.ServiceAddress
	}
	return ""
}

func (x *RegisterProtocolRangeRequest) GetStartProtocol() int32 {
	if x != nil {
		return x.StartProtocol
	}
	return 0
}

func (x *RegisterProtocolRangeRequest) GetEndProtocol() int32 {
	if x != nil {
		return x.EndProtocol
	}
	return 0
}

// RegisterProtocolRangeResponse 注册协议编号段响应
type RegisterProtocolRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterProtocolRangeResponse) Reset() {
	*x = RegisterProtocolRangeResponse{}
	mi := &file_test_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterProtocolRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterProtocolRangeResponse) ProtoMessage() {}

func (x *RegisterProtocolRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterProtocolRangeResponse.ProtoReflect.Descriptor instead.
func (*RegisterProtocolRangeResponse) Descriptor() ([]byte, []int) {
	return file_test_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterProtocolRangeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterProtocolRangeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_test_gateway_proto protoreflect.FileDescriptor

const file_test_gateway_proto_rawDesc = "" +
	"\n" +
	"\x12test_gateway.proto\x12\agateway\"\xb4\x01\n" +
	"\x1cRegisterProtocolRangeRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12'\n" +
	"\x0fservice_address\x18\x02 \x01(\tR\x0eserviceAddress\x12%\n" +
	"\x0estart_protocol\x18\x03 \x01(\x05R\rstartProtocol\x12!\n" +
	"\fend_protocol\x18\x04 \x01(\x05R\vendProtocol\"O\n" +
	"\x1dRegisterProtocolRangeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2z\n" +
	"\x0eGatewayService\x12h\n" +
	"\x15RegisterProtocolRange\x12%.gateway.RegisterProtocolRangeRequest\x1a&.gateway.RegisterProtocolRangeResponse\"\x00B&Z$github.com/aoyo/qp/pkg/proto/gatewayb\x06proto3"

var (
	file_test_gateway_proto_rawDescOnce sync.Once
	file_test_gateway_proto_rawDescData []byte
)

func file_test_gateway_proto_rawDescGZIP() []byte {
	file_test_gateway_proto_rawDescOnce.Do(func() {
		file_test_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_gateway_proto_rawDesc), len(file_test_gateway_proto_rawDesc)))
	})
	return file_test_gateway_proto_rawDescData
}

var file_test_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_gateway_proto_goTypes = []any{
	(*RegisterProtocolRangeRequest)(nil),  // 0: gateway.RegisterProtocolRangeRequest
	(*RegisterProtocolRangeResponse)(nil), // 1: gateway.RegisterProtocolRangeResponse
}
var file_test_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.GatewayService.RegisterProtocolRange:input_type -> gateway.RegisterProtocolRangeRequest
	1, // 1: gateway.GatewayService.RegisterProtocolRange:output_type -> gateway.RegisterProtocolRangeResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_gateway_proto_init() }
func file_test_gateway_proto_init() {
	if File_test_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_gateway_proto_rawDesc), len(file_test_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_gateway_proto_goTypes,
		DependencyIndexes: file_test_gateway_proto_depIdxs,
		MessageInfos:      file_test_gateway_proto_msgTypes,
	}.Build()
	File_test_gateway_proto = out.File
	file_test_gateway_proto_goTypes = nil
	file_test_gateway_proto_depIdxs = nil
}
